package status_pages

import "github.com/metoro-io/statusphere/common/api"

var StatusPages = []api.StatusPage{
	{
		URL:  "https://status.appveyor.com",
		Name: "AppVeyor",
	}, {
		URL:  "https://status.aviator.co",
		Name: "Aviator",
	}, {
		URL:  "https://status.bitrise.io",
		Name: "Bitrise",
	}, {
		URL:  "https://status.circleci.com",
		Name: "Circle CI",
	}, {
		URL:  "https://status.cloudmqtt.com",
		Name: "CloudMQTT",
	}, {
		URL:  "http://status.codefresh.io",
		Name: "codefresh",
	}, {
		URL:  "http://codeship.statuspage.io",
		Name: "codeship",
	}, {
		URL:  "https://currents.instatus.com",
		Name: "Currents",
	}, {
		URL:  "https://status.digitalpigeon.com",
		Name: "Digital Pigeon",
	}, {
		URL:  "https://status.gathercontent.com/#",
		Name: "GatherContent",
	}, {
		URL:  "https://status.harness.io",
		Name: "harness",
	}, {
		URL:  "https://status.hasura.io",
		Name: "hasura",
	}, {
		URL:  "https://status.jellyfish.co",
		Name: "jellyfish",
	}, {
		URL:  "https://status.jenkins.io",
		Name: "jenkins",
	}, {
		URL:  "https://status.nintex.com",
		Name: "nintex",
	}, {
		URL:  "https://status.keypup.io",
		Name: "keypup",
	}, {
		URL:  "https://status.maestroqa.com",
		Name: "maestroqa",
	}, {
		URL:  "https://status.lingk.io",
		Name: "lingk",
	}, {
		URL:  "https://status.octopus.com",
		Name: "octopus",
	}, {
		URL:  "https://pdq.statuspage.io",
		Name: "pdq",
	}, {
		URL:  "https://permit-io.instatus.com",
		Name: "permit-io",
	}, {
		URL:  "https://prefect.status.io",
		Name: "prefect",
	}, {
		URL:  "https://status.telerik.com",
		Name: "progress-telerik",
	}, {
		URL:  "https://status.pulumi.com",
		Name: "pulumi",
	}, {
		URL:  "http://status.semaphoreci.com",
		Name: "semaphore",
	}, {
		URL:  "https://status.servicerocket.com",
		Name: "servicerocket",
	}, {
		URL:  "https://app-status.sharegate.com",
		Name: "sharegate",
	}, {
		URL:  "https://simplyq.statuspage.io",
		Name: "simplyq",
	}, {
		URL:  "https://status.sleuth.io",
		Name: "sleuth",
	}, {
		URL:  "https://spacelift.statuspage.io",
		Name: "spacelift",
	}, {
		URL:  "https://status.subsplash.com",
		Name: "subsplash",
	}, {
		URL:  "https://status.temporal.io",
		Name: "temporal",
	}, {
		URL:  "https://status.thruinc.com",
		Name: "thru",
	}, {
		URL:  "https://rootly.com/teams/layerci/status-pages/webapp-io-status-page/public",
		Name: "webappio",
	}, {
		URL:  "https://xporter.statuspage.io",
		Name: "xporter",
	}, {
		URL:  "https://status.acquia.com",
		Name: "acquia",
	}, {
		URL:  "https://status.actionstep.com",
		Name: "actionstep",
	}, {
		URL:  "https://status.adalo.com",
		Name: "adalo",
	}, {
		URL:  "https://status.connect.adaptavist.com",
		Name: "adaptavist-cloud-apps",
	}, {
		URL:  "https://edgedns.status.akamai.com",
		Name: "akamai-edge-dns",
	}, {
		URL:  "https://status.alibabacloud.com",
		Name: "alibaba-cloud",
	}, {
		URL:  "https://status.alphavps.com",
		Name: "alphavps",
	}, {
		URL:  "https://status.aws.amazon.com",
		Name: "amazon-web-services",
	}, {
		URL:  "https://status.apaleo.com",
		Name: "apaleo",
	}, {
		URL:  "https://status.apigee.com",
		Name: "apigee",
	}, {
		URL:  "https://www.appian.com/trust/status",
		Name: "appian",
	}, {
		URL:  "https://www.apple.com/support/systemstatus",
		Name: "apple",
	}, {
		URL:  "https://developer.apple.com/system-status",
		Name: "apple-developer",
	}, {
		URL:  "https://status.appsflyer.com",
		Name: "appsflyer",
	}, {
		URL:  "https://status.aquasec.com",
		Name: "aqua",
	}, {
		URL:  "https://status.arista.io",
		Name: "arista-cloudvision",
	}, {
		URL:  "https://status.armor.com",
		Name: "armor",
	}, {
		URL:  "https://status.aspex.be",
		Name: "aspex",
	}, {
		URL:  "https://athennian.statuspage.io",
		Name: "athennian",
	}, {
		URL:  "https://status.avanan.com",
		Name: "avanan",
	}, {
		URL:  "https://status.avayacloud.com",
		Name: "avaya-cloud",
	}, {
		URL:  "https://status.axcient.com",
		Name: "axcient",
	}, {
		URL:  "https://status.axiom.co",
		Name: "axiom",
	}, {
		URL:  "https://azure.microsoft.com/en-us/status",
		Name: "azure",
	}, {
		URL:  "https://status.balena.io",
		Name: "balena",
	}, {
		URL:  "http://status.bandwidth.com",
		Name: "bandwidth",
	}, {
		URL:  "https://www.bexio-status.com",
		Name: "bexio",
	}, {
		URL:  "https://status.bittitan.com",
		Name: "bittitan",
	}, {
		URL:  "https://status.bizzabo.com",
		Name: "bizzabo",
	}, {
		URL:  "https://status.blend.com",
		Name: "blend",
	}, {
		URL:  "http://status.bluejeans.com",
		Name: "bluejeans",
	}, {
		URL:  "https://status.bluejeans.com",
		Name: "blue-jeans-network",
	}, {
		URL:  "https://status.brivo.com",
		Name: "brivo",
	}, {
		URL:  "https://status.broadcom.com/services/cloud-secure-web-gateway",
		Name: "broadcom-cloud-swg",
	}, {
		URL:  "https://status.broadcom.com/services/arcot",
		Name: "broadcom-arcot",
	}, {
		URL:  "https://cdd.status.broadcom.com",
		Name: "broadcom-continuous-delivery-director",
	}, {
		URL:  "https://dx.status.broadcom.com",
		Name: "broadcom-dx-saas",
	}, {
		URL:  "https://status.broadcom.com/services/edge-secure-web-gateway",
		Name: "broadcom-edge-secure-web-gateway",
	}, {
		URL:  "https://layer7.status.broadcom.com",
		Name: "broadcom-layer7-api-management",
	}, {
		URL:  "https://status.broadcom.com/services/rally",
		Name: "broadcom-rally",
	}, {
		URL:  "https://status.broadcom.com/services/symantec-endpoint-security-enterprise",
		Name: "broadcom-symantec-endpoint-security-enterprise",
	}, {
		URL:  "https://status.bunny.net",
		Name: "bunny",
	}, {
		URL:  "https://trust.calix.com",
		Name: "calix",
	}, {
		URL:  "https://status.casewarecloud.com",
		Name: "caseware-cloud",
	}, {
		URL:  "https://status.catalystcloud.nz",
		Name: "catalyst-cloud",
	}, {
		URL:  "https://status.ceros.com",
		Name: "ceros",
	}, {
		URL:  "https://status.chromatic.com",
		Name: "chromatic",
	}, {
		URL:  "https://status.ciscoiot.com",
		Name: "cisco-iot",
	}, {
		URL:  "https://status.amp.cisco.com",
		Name: "cisco-secure-endpoint",
	}, {
		URL:  "https://status.umbrella.com",
		Name: "cisco-umbrella",
	}, {
		URL:  "https://status.cloud.com",
		Name: "citrix-cloud",
	}, {
		URL:  "http://status.cloud66.com",
		Name: "cloud-66",
	}, {
		URL:  "https://status.connect.cloudblue.com",
		Name: "cloudblue-connect",
	}, {
		URL:  "https://trust.cloudcheckr.com",
		Name: "cloudcheckr",
	}, {
		URL:  "https://status.cloudera.com",
		Name: "cloudera",
	}, {
		URL:  "https://status.cloudfanatic.net",
		Name: "cloudfanatic",
	}, {
		URL:  "https://status.cloudsigma.com",
		Name: "cloudsigma",
	}, {
		URL:  "http://status.cloudways.com",
		Name: "cloudways",
	}, {
		URL:  "https://status.cockroachlabs.cloud",
		Name: "cockroach-labs",
	}, {
		URL:  "https://status.cocoapods.org",
		Name: "cocoapods",
	}, {
		URL:  "https://status.confluent.cloud",
		Name: "confluent",
	}, {
		URL:  "https://status.coreweave.com",
		Name: "coreweave",
	}, {
		URL:  "https://status.cloud.coveo.com",
		Name: "coveo-cloud",
	}, {
		URL:  "https://status.cradlepoint.com",
		Name: "cradlepoint",
	}, {
		URL:  "https://status.current-rms.com",
		Name: "current-rms",
	}, {
		URL:  "https://status.databox.com",
		Name: "databox",
	}, {
		URL:  "https://status.datarobot.com",
		Name: "datarobot",
	}, {
		URL:  "https://status.getdbt.com",
		Name: "dbt-cloud",
	}, {
		URL:  "http://www.dediservestatus.com",
		Name: "dediserve",
	}, {
		URL:  "https://status.boomi.com",
		Name: "dell-boomi",
	}, {
		URL:  "https://status.digitalocean.com",
		Name: "digitalocean",
	}, {
		URL:  "https://status.divio.com",
		Name: "divio",
	}, {
		URL:  "https://dnsstatus.com",
		Name: "dns-made-easy",
	}, {
		URL:  "https://docevent.instatus.com",
		Name: "docevent",
	}, {
		URL:  "https://status.dogado.de",
		Name: "dogado",
	}, {
		URL:  "https://status.doit.com",
		Name: "doit",
	}, {
		URL:  "https://status.dongee.com",
		Name: "dongee",
	}, {
		URL:  "https://www.dopplerstatus.com",
		Name: "doppler",
	}, {
		URL:  "https://status.drchrono.com",
		Name: "drchrono",
	}, {
		URL:  "https://status.drmtoday.com",
		Name: "drmtoday",
	}, {
		URL:  "https://status.dronedeploy.com",
		Name: "dronedeploy",
	}, {
		URL:  "https://www.dynstatus.com",
		Name: "dyn",
	}, {
		URL:  "http://status.dynamixcloud.com",
		Name: "dynamix-cloud",
	}, {
		URL:  "https://dynatrace.status.io",
		Name: "dynatrace",
	}, {
		URL:  "https://www.easypoststatus.com",
		Name: "easypost",
	}, {
		URL:  "https://status.ecostruxureit.com",
		Name: "ecostruxure-it",
	}, {
		URL:  "https://status.egnyte.com",
		Name: "egnyte",
	}, {
		URL:  "https://ukstatus.ek.co",
		Name: "ekco",
	}, {
		URL:  "https://status.elastic.io",
		Name: "elasticio",
	}, {
		URL:  "https://status.elluciancloud.com",
		Name: "ellucian",
	}, {
		URL:  "https://status.emnify.com",
		Name: "emnify",
	}, {
		URL:  "http://status.empist.com",
		Name: "empist",
	}, {
		URL:  "https://engineyard.statuspage.io",
		Name: "engine-yard",
	}, {
		URL:  "https://www.trustesker.com",
		Name: "esker",
	}, {
		URL:  "https://statut.eurafibre.fr",
		Name: "eurafibre",
	}, {
		URL:  "https://exoscalestatus.com",
		Name: "exoscale",
	}, {
		URL:  "https://www.f5cloudstatus.com",
		Name: "f5",
	}, {
		URL:  "http://status.filestack.com",
		Name: "filepicker",
	}, {
		URL:  "https://status.firebase.google.com",
		Name: "firebase",
	}, {
		URL:  "https://flagsmith.statuspage.io",
		Name: "flagsmith",
	}, {
		URL:  "https://status.flatfile.io",
		Name: "flatfile",
	}, {
		URL:  "https://status.flow.swiss",
		Name: "flow-swiss",
	}, {
		URL:  "https://status.fly.io",
		Name: "flyio",
	}, {
		URL:  "https://forticlient-status.forticloud.com",
		Name: "forticlient-cloud",
	}, {
		URL:  "https://status.fortiweb-cloud.com",
		Name: "fortiweb-cloud",
	}, {
		URL:  "https://status.freshbooks.com",
		Name: "freshbooks",
	}, {
		URL:  "https://crmstatus.freshworks.com",
		Name: "freshworks-crm",
	}, {
		URL:  "https://status.frontify.com",
		Name: "frontify",
	}, {
		URL:  "https://status.gathercontent.com/#",
		Name: "gathercontent",
	}, {
		URL:  "https://statuspage.gcorelabs.com",
		Name: "g-core-labs",
	}, {
		URL:  "https://status.mypurecloud.com",
		Name: "genesys-cloud",
	}, {
		URL:  "https://status.gitlabhost.com",
		Name: "gitlabhost",
	}, {
		URL:  "https://status.glesys.com",
		Name: "glesys",
	}, {
		URL:  "https://status.cloud.google.com",
		Name: "google-cloud",
	}, {
		URL:  "https://status.cloud.google.com/maps-platform",
		Name: "google-maps-platform",
	}, {
		URL:  "https://status.g-portal.com",
		Name: "gportal",
	}, {
		URL:  "https://status.granicusops.com",
		Name: "granicus",
	}, {
		URL:  "https://status.grncld.net",
		Name: "green-cloud-technologies",
	}, {
		URL:  "https://status.guidewire.com",
		Name: "guidewire",
	}, {
		URL:  "https://status.hashicorp.com",
		Name: "hashicorp",
	}, {
		URL:  "https://www.heartstatus.uk",
		Name: "heart-internet",
	}, {
		URL:  "https://status.heroku.com",
		Name: "heroku",
	}, {
		URL:  "https://status.hetzner.com",
		Name: "hetzner",
	}, {
		URL:  "https://status.hevodata.com",
		Name: "hevo",
	}, {
		URL:  "https://status.hivebrite.com",
		Name: "hivebrite",
	}, {
		URL:  "https://status.hostifi.com",
		Name: "hostifi",
	}, {
		URL:  "https://www.hostpapastatus.com",
		Name: "hostpapa",
	}, {
		URL:  "https://status.aspera.io",
		Name: "ibm-aspera",
	}, {
		URL:  "https://cloud.ibm.com/status?selected=status",
		Name: "ibm-cloud",
	}, {
		URL:  "https://status.infoblox.com",
		Name: "infoblox",
	}, {
		URL:  "https://status.ingage.jp",
		Name: "ingage",
	}, {
		URL:  "https://status.inspera.no",
		Name: "inspera",
	}, {
		URL:  "https://status.ionos.cloud",
		Name: "ionos-cloud",
	}, {
		URL:  "https://www.iscorp.com/outage-status",
		Name: "iscorp",
	}, {
		URL:  "https://status.ivanticloud.com",
		Name: "ivanti-cloud",
	}, {
		URL:  "https://status.jamasoftware.com",
		Name: "jama-software",
	}, {
		URL:  "https://status.jitpack.io",
		Name: "jitpack",
	}, {
		URL:  "http://status.juicefs.io",
		Name: "juicefs",
	}, {
		URL:  "https://status.k6.io",
		Name: "k6",
	}, {
		URL:  "https://status.keypup.io",
		Name: "keypup",
	}, {
		URL:  "https://status.kinghost.net.br",
		Name: "kinghost",
	}, {
		URL:  "https://status.kualo.com",
		Name: "kualo",
	}, {
		URL:  "https://status.layerstack.com",
		Name: "layerstack",
	}, {
		URL:  "https://www.leasewebstatus.com",
		Name: "leaseweb",
	}, {
		URL:  "http://status.lifesizecloud.com",
		Name: "lifesize-cloud",
	}, {
		URL:  "https://status.lightstep.com",
		Name: "lightstep",
	}, {
		URL:  "https://status.lingk.io",
		Name: "lingk",
	}, {
		URL:  "https://status.linode.com",
		Name: "linode",
	}, {
		URL:  "https://status.liveramp.com",
		Name: "liveramp",
	}, {
		URL:  "https://status.logz.io",
		Name: "logz",
	}, {
		URL:  "https://status.loopup.com",
		Name: "loopup",
	}, {
		URL:  "https://status.lotame.com",
		Name: "lotame",
	}, {
		URL:  "https://status.lumaserv.com",
		Name: "lumaserv",
	}, {
		URL:  "https://status.magemojo.com",
		Name: "magemojo",
	}, {
		URL:  "https://status.magnusbox.com",
		Name: "magnus-box",
	}, {
		URL:  "https://status.matillion.com",
		Name: "matillion",
	}, {
		URL:  "https://status.mavenlink.com",
		Name: "mavenlink-",
	}, {
		URL:  "https://oneview.mitel.com/s/trust",
		Name: "micloud-connect",
	}, {
		URL:  "https://neonstatus.com",
		Name: "neon",
	}, {
		URL:  "https://status.services.cloud.netapp.com",
		Name: "netapp",
	}, {
		URL:  "https://trust.netfortris.com",
		Name: "netfortris",
	}, {
		URL:  "https://netlifystatus.com",
		Name: "netlify",
	}, {
		URL:  "https://trust.netskope.com",
		Name: "netskope",
	}, {
		URL:  "https://ngenix.statuspage.io",
		Name: "ngenix",
	}, {
		URL:  "https://status.nhost.io",
		Name: "nhost",
	}, {
		URL:  "https://status.cloud.coop",
		Name: "nisc-cloud",
	}, {
		URL:  "https://ns1status.com",
		Name: "ns1",
	}, {
		URL:  "https://status.nutanix.com",
		Name: "nutanix",
	}, {
		URL:  "https://status.nylas.com",
		Name: "nylas",
	}, {
		URL:  "https://sorry.opencrm.co.uk",
		Name: "opencrm",
	}, {
		URL:  "https://www.opensrsstatus.com",
		Name: "opensrs",
	}, {
		URL:  "https://status.openvpn.com",
		Name: "openvpn",
	}, {
		URL:  "https://ocistatus.oraclecloud.com",
		Name: "oracle-cloud",
	}, {
		URL:  "https://status.otava.com",
		Name: "otava",
	}, {
		URL:  "https://status.us.ovhcloud.com",
		Name: "ovhcloud",
	}, {
		URL:  "http://status.packet.net",
		Name: "packet",
	}, {
		URL:  "https://status.paperspace.com",
		Name: "paperspace",
	}, {
		URL:  "https://status.perimeterx.com",
		Name: "perimeterx",
	}, {
		URL:  "https://status.pingplotter.cloud",
		Name: "pingplotter-cloud",
	}, {
		URL:  "https://status.platform9.com",
		Name: "platform9",
	}, {
		URL:  "https://status.platform.sh",
		Name: "platformsh",
	}, {
		URL:  "https://status.playfab.com",
		Name: "playfab",
	}, {
		URL:  "https://status.playvox.com",
		Name: "playvox",
	}, {
		URL:  "https://status.plumvoice.com",
		Name: "plum-voice",
	}, {
		URL:  "https://status.plusserver.com",
		Name: "plusserver",
	}, {
		URL:  "https://status.practicefusion.com",
		Name: "practice-fusion",
	}, {
		URL:  "https://status.presslabs.com",
		Name: "presslabs",
	}, {
		URL:  "https://status.kofaxcloud.com",
		Name: "printix",
	}, {
		URL:  "https://status.prismacloud.com",
		Name: "prisma-cloud",
	}, {
		URL:  "http://status.pubnub.com",
		Name: "pubnub",
	}, {
		URL:  "https://status.qlikcloud.com",
		Name: "qlik",
	}, {
		URL:  "https://status.quay.io",
		Name: "quay",
	}, {
		URL:  "https://status.racknerd.com",
		Name: "racknerd",
	}, {
		URL:  "https://status.apps.rackspace.com",
		Name: "rackspace",
	}, {
		URL:  "https://cwaf.status.radwarecloud.com",
		Name: "radware-cloud-waf",
	}, {
		URL:  "https://railway.instatus.com",
		Name: "railway",
	}, {
		URL:  "https://status.redcanary.com",
		Name: "red-canary",
	}, {
		URL:  "https://status.redhat.com",
		Name: "red-hat",
	}, {
		URL:  "https://status.redisgreen.net/services/1",
		Name: "redisgreen",
	}, {
		URL:  "https://status.render.com",
		Name: "render",
	}, {
		URL:  "http://status.reviewtrackers.com",
		Name: "reviewtrackers",
	}, {
		URL:  "https://status.ringover.com",
		Name: "ringover",
	}, {
		URL:  "https://status.rivery.io",
		Name: "rivery",
	}, {
		URL:  "https://www.roamstatus.com",
		Name: "roam",
	}, {
		URL:  "https://cspreporter.nl/storingen",
		Name: "rout-it",
	}, {
		URL:  "https://status.rubrik.com",
		Name: "rubrik",
	}, {
		URL:  "https://status.sailpoint.com",
		Name: "sailpoint",
	}, {
		URL:  "https://status.support.sap.com",
		Name: "sap-for-me--sap-one-support-launchpad",
	}, {
		URL:  "https://status.scaleway.com",
		Name: "Scaleway",
	}, {
		URL:  "https://scalingostatus.com",
		Name: "Scalingo",
	}, {
		URL:  "https://status.cloud.scorm.com",
		Name: "SCORM Cloud",
	}, {
		URL:  "https://status.scoutdns.com",
		Name: "ScoutDNS",
	}, {
		URL:  "https://status.section.io",
		Name: "Section",
	}, {
		URL:  "https://serveboltstatus.com",
		Name: "Servebolt",
	}, {
		URL:  "https://status.mysau.com.au",
		Name: "Servers Australia",
	}, {
		URL:  "https://sgtest1.statuspage.io",
		Name: "SG Test",
	}, {
		URL:  "https://status.sherweb.com",
		Name: "Sherweb",
	}, {
		URL:  "https://status.shockbyte.com",
		Name: "Shockbyte",
	}, {
		URL:  "https://status.eu0.signalfx.com",
		Name: "SignalFx EU0",
	}, {
		URL:  "https://status.us0.signalfx.com",
		Name: "SignalFx US0",
	}, {
		URL:  "https://status.us1.signalfx.com",
		Name: "SignalFx US1",
	}, {
		URL:  "https://status.simplyhosting.com",
		Name: "Simply Hosting & Servers",
	}, {
		URL:  "https://status.skykick.com",
		Name: "SkyKick",
	}, {
		URL:  "https://status.skysilk.com",
		Name: "SkySilk",
	}, {
		URL:  "https://status.smugmug.com",
		Name: "SmugMug",
	}, {
		URL:  "https://trust.snaplogic.com",
		Name: "SnapLogic",
	}, {
		URL:  "https://status.snapsheetclaims.com",
		Name: "Snapsheet",
	}, {
		URL:  "https://status.loggly.com",
		Name: "SolarWinds Loggly",
	}, {
		URL:  "https://status.soracom.com",
		Name: "Soracom",
	}, {
		URL:  "https://status.spiceworks.com",
		Name: "Spiceworks",
	}, {
		URL:  "https://status.spscommerce.com",
		Name: "SPS Commerce",
	}, {
		URL:  "https://status.stackpath.com",
		Name: "StackPath",
	}, {
		URL:  "https://status.storj.io",
		Name: "Storj",
	}, {
		URL:  "https://status.sugarsync.com",
		Name: "SugarSync",
	}, {
		URL:  "http://status.us1.sumologic.com",
		Name: "Sumo Logic US1",
	}, {
		URL:  "https://status.taloflow.ai",
		Name: "Taloflow",
	}, {
		URL:  "https://status.teradici.com",
		Name: "Teradici",
	}, {
		URL:  "https://www.teraswitchstatus.com",
		Name: "TeraSwitch",
	}, {
		URL:  "https://status.thousandeyes.com",
		Name: "ThousandEyes",
	}, {
		URL:  "https://status.cloud.tibco.com",
		Name: "TIBCO",
	}, {
		URL:  "https://status.flood.io",
		Name: "Tricentis Flood",
	}, {
		URL:  "https://status.trifacta.com",
		Name: "Trifacta",
	}, {
		URL:  "https://status.trinetcloud.com",
		Name: "TriNet",
	}, {
		URL:  "https://status.ubidots.com",
		Name: "Ubidots",
	}, {
		URL:  "http://status.ujet.co",
		Name: "UJET",
	}, {
		URL:  "https://status.ultradns.com",
		Name: "UltraDNS",
	}, {
		URL:  "https://status.umbraco.io",
		Name: "Umbraco Cloud",
	}, {
		URL:  "https://status.uniflowonline.com",
		Name: "uniFLOW Online",
	}, {
		URL:  "https://status.united-hoster.de",
		Name: "United Hoster GmbH",
	}, {
		URL:  "https://status.upcloud.com",
		Name: "UpCloud",
	}, {
		URL:  "https://status.uploadcare.com",
		Name: "Uploadcare",
	}, {
		URL:  "https://status.velocityhost.com.au",
		Name: "Velocity Host",
	}, {
		URL:  "https://www.vercel-status.com",
		Name: "Vercel",
	}, {
		URL:  "https://status.vetspire.com",
		Name: "Vetspire",
	}, {
		URL:  "https://status.vgrid.nz",
		Name: "vGRID Cloud Services",
	}, {
		URL:  "https://status.vmware-services.io",
		Name: "VMWare Cloud Services",
	}, {
		URL:  "https://status.voltage.cloud",
		Name: "Voltage",
	}, {
		URL:  "https://businesssupport.vonage.com/trust",
		Name: "Vonage Business",
	}, {
		URL:  "https://status.voximplant.com",
		Name: "Voximplant",
	}, {
		URL:  "https://status.vpsserver.com",
		Name: "VPSServer",
	}, {
		URL:  "https://status.vultr.com",
		Name: "Vultr",
	}, {
		URL:  "https://status.walkme.com",
		Name: "Walkme",
	}, {
		URL:  "https://status.wasabi.com",
		Name: "Wasabi",
	}, {
		URL:  "https://webdam-status.bynder.com",
		Name: "Webdam",
	}, {
		URL:  "https://status.webshare.io",
		Name: "Webshare",
	}, {
		URL:  "https://status.wiz.io",
		Name: "Wiz",
	}, {
		URL:  "https://status.workiva.com",
		Name: "Workiva",
	}, {
		URL:  "https://status.cloud.yandex.com/dashboard",
		Name: "Yandex Cloud",
	}, {
		URL:  "https://status.yasoon.com",
		Name: "yasoon",
	}, {
		URL:  "https://status.zenqms.com",
		Name: "ZenQMS",
	}, {
		URL:  "https://trust.zscaler.com/cloud-status",
		Name: "Zscaler Cloud",
	}, {
		URL:  "https://status.aiven.io",
		Name: "Aiven",
	}, {
		URL:  "https://status.algolia.com",
		Name: "Algolia",
	}, {
		URL:  "http://status.apollographql.com",
		Name: "Apollo",
	}, {
		URL:  "https://status.basedash.com",
		Name: "Basedash",
	}, {
		URL:  "https://status.bonsai.io",
		Name: "Bonsai Elasticsearch",
	}, {
		URL:  "https://status.cockroachlabs.cloud",
		Name: "Cockroach Labs",
	}, {
		URL:  "https://www.collibra.com/us/en/status-dashboard",
		Name: "Collibra",
	}, {
		URL:  "https://cloud-status.elastic.co",
		Name: "Elastic Cloud",
	}, {
		URL:  "https://status.fauna.com",
		Name: "Fauna",
	}, {
		URL:  "https://status.fivetran.com",
		Name: "Fivetran",
	}, {
		URL:  "https://grafanalabs.statuspage.io",
		Name: "Grafana",
	}, {
		URL:  "http://status.graphenedb.com",
		Name: "GrapheneDB",
	}, {
		URL:  "https://status.influxdata.com",
		Name: "InfluxData",
	}, {
		URL:  "https://status.instaclustr.com",
		Name: "Instaclustr",
	}, {
		URL:  "https://status.iron.io",
		Name: "Iron.io",
	}, {
		URL:  "https://status.keypup.io",
		Name: "Keypup",
	}, {
		URL:  "http://status.memcachier.com",
		Name: "Memcachier",
	}, {
		URL:  "https://status.modeanalytics.com",
		Name: "Mode",
	}, {
		URL:  "http://status.cloud.mongodb.com",
		Name: "MongoDB",
	}, {
		URL:  "https://status.neo4j.io",
		Name: "Neo4j Aura",
	}, {
		URL:  "https://neonstatus.com",
		Name: "Neon",
	}, {
		URL:  "https://status.northflank.com",
		Name: "Northflank",
	}, {
		URL:  "http://status.objectrocket.com",
		Name: "ObjectRocket",
	}, {
		URL:  "https://status.opencorporates.com",
		Name: "OpenCorporates",
	}, {
		URL:  "https://status.pgmustard.com",
		Name: "pgMustard",
	}, {
		URL:  "https://status.pinecone.io",
		Name: "Pinecone",
	}, {
		URL:  "https://www.planetscalestatus.com",
		Name: "PlanetScale",
	}, {
		URL:  "https://popsqlstatus.com",
		Name: "PopSQL",
	}, {
		URL:  "https://status.redis.com",
		Name: "Redis",
	}, {
		URL:  "http://status.redistogo.com",
		Name: "RedisToGo",
	}, {
		URL:  "http://status.searchly.com",
		Name: "Searchly",
	}, {
		URL:  "https://status.snowflake.com",
		Name: "Snowflake",
	}, {
		URL:  "https://status.stacker.app",
		Name: "Stacker",
	}, {
		URL:  "https://status.stitchdata.com",
		Name: "Stitch Data",
	}, {
		URL:  "https://status.supabase.com",
		Name: "Supabase",
	}, {
		URL:  "http://status.swiftype.com",
		Name: "Swiftype",
	}, {
		URL:  "https://trust.talend.com",
		Name: "Talend",
	}, {
		URL:  "https://status.timescale.com",
		Name: "Timescale",
	}, {
		URL:  "https://timezonedb.com/status",
		Name: "TimezoneDB",
	}, {
		URL:  "https://status.upstash.com",
		Name: "Upstash",
	}, {
		URL:  "https://status.zilliz.com/uptime",
		Name: "illiz",
	}, {
		URL:  "https://edgedns.status.akamai.com",
		Name: "Akamai Edge DNS",
	}, {
		URL:  "https://status.api.video",
		Name: "api.video",
	}, {
		URL:  "https://status.brandfetch.io",
		Name: "Brandfetch",
	}, {
		URL:  "https://status.bunny.net",
		Name: "Bunny",
	}, {
		URL:  "https://client.cdn77.com/support/status",
		Name: "CDN77",
	}, {
		URL:  "https://status.cdnjs.com",
		Name: "Cdnjs",
	}, {
		URL:  "https://status.clearlyip.com",
		Name: "ClearlyIP",
	}, {
		URL:  "https://www.cloudflarestatus.com",
		Name: "Cloudflare",
	}, {
		URL:  "https://status.digitalpigeon.com",
		Name: "Digital Pigeon",
	}, {
		URL:  "https://status.dracoon.com",
		Name: "DRACOON",
	}, {
		URL:  "https://status.edg.io",
		Name: "Edgio",
	}, {
		URL:  "https://status.fasterize.com",
		Name: "Fasterize",
	}, {
		URL:  "https://www.fastlystatus.com",
		Name: "Fastly",
	}, {
		URL:  "https://status.files.com",
		Name: "Files",
	}, {
		URL:  "https://status.fortawesome.com",
		Name: "Font Awesome",
	}, {
		URL:  "https://status.graphcdn.io",
		Name: "GraphCDN",
	}, {
		URL:  "https://status.hygraph.com",
		Name: "Hygraph",
	}, {
		URL:  "https://statuspage.imagekit.io",
		Name: "ImageKit",
	}, {
		URL:  "https://status.imgix.com",
		Name: "imgix",
	}, {
		URL:  "https://status.internetx.com",
		Name: "InterNetX",
	}, {
		URL:  "https://status.iristel.com",
		Name: "Iristel",
	}, {
		URL:  "https://trust.jitterbit.com",
		Name: "Jitterbit",
	}, {
		URL:  "https://status.jsdelivr.com",
		Name: "JSDelivr",
	}, {
		URL:  "https://status.keycdn.com",
		Name: "KeyCDN",
	}, {
		URL:  "https://status.littledata.io",
		Name: "Littledata",
	}, {
		URL:  "https://status.m247.com",
		Name: "M247",
	}, {
		URL:  "https://status.mist.com",
		Name: "Mist",
	}, {
		URL:  "https://trust.netskope.com",
		Name: "Netskope",
	}, {
		URL:  "https://ngenix.statuspage.io",
		Name: "NGENIX",
	}, {
		URL:  "https://status.teleport.sh",
		Name: "Teleport",
	}, {
		URL:  "https://status.twingate.com",
		Name: "Twingate",
	}, {
		URL:  "https://status.uniflowonline.com",
		Name: "uniFLOW Online",
	}, {
		URL:  "https://status.upcloud.com",
		Name: "UpCloud",
	}, {
		URL:  "https://status.uploadcare.com",
		Name: "Uploadcare",
	}, {
		URL:  "https://status.verizondigitalmedia.com/#network-status",
		Name: "Verizon Digital Media",
	}, {
		URL:  "https://wetransfer.statuspage.io",
		Name: "WeTransfer",
	}, {
		URL:  "https://status.alchemy.com",
		Name: "Alchemy",
	}, {
		URL:  "https://status.b2c2.com",
		Name: "B2C2",
	}, {
		URL:  "https://bitfinex.statuspage.io",
		Name: "Bitfinex",
	}, {
		URL:  "https://status.bitgo.com",
		Name: "BitGo",
	}, {
		URL:  "https://status.bitmex.com",
		Name: "BitMEX",
	}, {
		URL:  "https://status.bitpanda.com",
		Name: "Bitpanda",
	}, {
		URL:  "https://status.bitso.com",
		Name: "Bitso",
	}, {
		URL:  "https://www.blockchain-status.com",
		Name: "Blockchain",
	}, {
		URL:  "https://status.blockchair.com",
		Name: "Blockchair",
	}, {
		URL:  "https://status.block.io",
		Name: "Block.io",
	}, {
		URL:  "https://status.bloom.co",
		Name: "Bloom",
	}, {
		URL:  "https://status.brave.com",
		Name: "Brave",
	}, {
		URL:  "https://status.cex.io",
		Name: "CEX.IO",
	}, {
		URL:  "https://status.chainalysis.com",
		Name: "Chainalysis",
	}, {
		URL:  "https://status.circle.com",
		Name: "Circle",
	}, {
		URL:  "https://status.cloudnovi.com",
		Name: "Cloudnovi",
	}, {
		URL:  "https://status.coinapi.io",
		Name: "CoinAPI.io",
	}, {
		URL:  "https://coinbase.statuspage.io",
		Name: "Coinbase",
	}, {
		URL:  "https://status.commerce.coinbase.com",
		Name: "Coinbase Commerce",
	}, {
		URL:  "https://status.prime.coinbase.com",
		Name: "Coinbase Prime",
	}, {
		URL:  "https://status.pro.coinbase.com",
		Name: "Coinbase Pro",
	}, {
		URL:  "https://status.coingate.com",
		Name: "CoinGate",
	}, {
		URL:  "https://status.coingecko.com",
		Name: "CoinGecko",
	}, {
		URL:  "https://status.coinjar.com",
		Name: "CoinJar",
	}, {
		URL:  "https://status.coinlist.co",
		Name: "CoinList",
	}, {
		URL:  "https://status.coinmarketcap.com",
		Name: "CoinMarketCap",
	}, {
		URL:  "https://status.coinmarketcap.com",
		Name: "Coins.ph",
	}, {
		URL:  "https://status.crypto.com",
		Name: "Crypto.com",
	}, {
		URL:  "https://status.cryptopro.app",
		Name: "Crypto Pro",
	}, {
		URL:  "https://www.enjinstatus.com",
		Name: "Enjin",
	}, {
		URL:  "https://etherscan.freshstatus.io",
		Name: "Etherscan",
	}, {
		URL:  "https://status.etoro.com",
		Name: "eToro",
	}, {
		URL:  "https://status.filecoin.io",
		Name: "Filecoin",
	}, {
		URL:  "https://status.fireblocks.com",
		Name: "Fireblocks",
	}, {
		URL:  "https://status.gemini.com",
		Name: "Gemini",
	}, {
		URL:  "https://status.hedera.com",
		Name: "Hedera",
	}, {
		URL:  "http://status.helium.com",
		Name: "Helium",
	}, {
		URL:  "https://status.hummingbot.io",
		Name: "Hummingbot",
	}, {
		URL:  "https://status.infura.io",
		Name: "Infura",
	}, {
		URL:  "https://status.kraken.com",
		Name: "Kraken",
	}, {
		URL:  "https://status.ledger.com",
		Name: "Ledger",
	}, {
		URL:  "https://status.lmax.com",
		Name: "LMAX",
	}, {
		URL:  "https://status.luno.com",
		Name: "Luno",
	}, {
		URL:  "https://status.mnemonichq.com",
		Name: "Mnemonic",
	}, {
		URL:  "https://status.nbatopshot.com",
		Name: "NBA Top Shot",
	}, {
		URL:  "https://status.opennode.co",
		Name: "OpenNode",
	}, {
		URL:  "https://status.opensea.io",
		Name: "OpenSea",
	}, {
		URL:  "https://status.optimism.io",
		Name: "Optimism",
	}, {
		URL:  "https://status.osl.com",
		Name: "OSL Singapore",
	}, {
		URL:  "https://status.paribu.com",
		Name: "Paribu",
	}, {
		URL:  "https://status.primexbt.com",
		Name: "PrimeXBT",
	}, {
		URL:  "https://status.purse.io",
		Name: "Purse.io",
	}, {
		URL:  "https://status.quadency.com",
		Name: "Quadency",
	}, {
		URL:  "https://status.quicknode.com",
		Name: "QuickNode",
	}, {
		URL:  "https://status.remitano.com",
		Name: "Remitano",
	}, {
		URL:  "https://status.shakepay.com",
		Name: "Shakepay",
	}, {
		URL:  "https://status.solana.com",
		Name: "Solana",
	}, {
		URL:  "https://status.thegraph.com",
		Name: "The Graph",
	}, {
		URL:  "https://status.uphold.com",
		Name: "Uphold",
	}, {
		URL:  "https://status.zerohash.com",
		Name: "Zero Hash",
	}, {
		URL:  "https://status.8base.com",
		Name: "8base",
	}, {
		URL:  "https://status.ably.com",
		Name: "Ably",
	}, {
		URL:  "https://status.airbrake.io",
		Name: "Airbrake",
	}, {
		URL:  "http://status.mws.amazon.com",
		Name: "Amazon Marketplace Web Service",
	}, {
		URL:  "https://status.useanvil.com",
		Name: "Anvil",
	}, {
		URL:  "https://status.apify.com",
		Name: "Apify",
	}, {
		URL:  "https://developer.apple.com/system-status",
		Name: "Apple Developer",
	}, {
		URL:  "https://status.appsignal.com",
		Name: "AppSignal",
	}, {
		URL:  "https://apwide.statuspage.io",
		Name: "Apwide",
	}, {
		URL:  "https://status.array.com",
		Name: "Array",
	}, {
		URL:  "https://status.ashbyhq.com",
		Name: "Ashby",
	}, {
		URL:  "https://status.assembla.com",
		Name: "Assembla",
	}, {
		URL:  "https://status.atlassian.com",
		Name: "Atlassian",
	}, {
		URL:  "https://compass.status.atlassian.com",
		Name: "Atlassian Compass",
	}, {
		URL:  "https://developer.status.atlassian.com",
		Name: "Atlassian Developer",
	}, {
		URL:  "https://bitbucket.status.atlassian.com",
		Name: "Bitbucket",
	}, {
		URL:  "https://status.bitrise.io",
		Name: "Bitrise",
	}, {
		URL:  "https://status.blazemeter.com",
		Name: "BlazeMeter",
	}, {
		URL:  "http://status.appneta.com",
		Name: "Broadcom AppNeta",
	}, {
		URL:  "https://status.bugsnag.com",
		Name: "Bugsnag",
	}, {
		URL:  "https://status.canonical.com",
		Name: "Canonical",
	}, {
		URL:  "https://status.circleci.com",
		Name: "Circle CI",
	}, {
		URL:  "https://www.clevercloudstatus.com",
		Name: "CleverCloud",
	}, {
		URL:  "http://status.clojars.org",
		Name: "Clojars",
	}, {
		URL:  "http://status.cloudamqp.com",
		Name: "CloudAMPQ",
	}, {
		URL:  "https://www.cloudbeesstatus.com",
		Name: "CloudBees",
	}, {
		URL:  "https://status.cloudnovi.com",
		Name: "Cloudnovi",
	}, {
		URL:  "https://status.cloudrepo.io",
		Name: "CloudRepo",
	}, {
		URL:  "https://status.cocoapods.org",
		Name: "CocoaPods",
	}, {
		URL:  "http://status.codefresh.io",
		Name: "Codefresh",
	}, {
		URL:  "https://confluence.status.atlassian.com",
		Name: "Confluence",
	}, {
		URL:  "https://status.coveralls.io",
		Name: "Coveralls",
	}, {
		URL:  "https://status.crates.io",
		Name: "crates.io",
	}, {
		URL:  "https://status.cubecloud.dev",
		Name: "Cube Cloud",
	}, {
		URL:  "https://status.cypress.io",
		Name: "Cypress",
	}, {
		URL:  "https://datacake-status.com",
		Name: "Datacake",
	}, {
		URL:  "https://status.datadoghq.com",
		Name: "Datadog",
	}, {
		URL:  "https://status.deadmanssnitch.com",
		Name: "Dead Man's Snitch",
	}, {
		URL:  "https://status.deepsource.io",
		Name: "DeepSource",
	}, {
		URL:  "https://denostatus.com",
		Name: "Deno Deploy",
	}, {
		URL:  "https://status.docebo.com",
		Name: "Docebo",
	}, {
		URL:  "https://status.esa.io",
		Name: "esa",
	}, {
		URL:  "https://status.esa.io",
		Name: "esa.io",
	}, {
		URL:  "https://flagsmith.statuspage.io",
		Name: "FlagSmith",
	}, {
		URL:  "https://status.formspree.io",
		Name: "Formspree",
	}, {
		URL:  "https://status.frigade.com",
		Name: "Frigade",
	}, {
		URL:  "https://status.gatsbyjs.com",
		Name: "Gastby",
	}, {
		URL:  "https://status.fury.co",
		Name: "Gemfury",
	}, {
		URL:  "https://status.ggnetwork.com",
		Name: "GGNetwork",
	}, {
		URL:  "https://ghostinspector.statuspage.io",
		Name: "Ghost Inspector",
	}, {
		URL:  "https://www.gitbookstatus.com",
		Name: "GitBook",
	}, {
		URL:  "https://status.glideapps.com",
		Name: "Glide apps",
	}, {
		URL:  "https://status.glitch.com",
		Name: "Glitch",
	}, {
		URL:  "http://stats.pingdom.com/xf7vwkfqygcb",
		Name: "Gremlin",
	}, {
		URL:  "https://status.harness.io",
		Name: "Harness",
	}, {
		URL:  "https://status.hashnode.com",
		Name: "Hashnode",
	}, {
		URL:  "https://status.hasura.io",
		Name: "Hasura",
	}, {
		URL:  "https://height.statuspage.io",
		Name: "Height",
	}, {
		URL:  "https://status.helpdocs.io",
		Name: "HelpDocs",
	}, {
		URL:  "https://status.herocoders.com",
		Name: "HeroCoders",
	}, {
		URL:  "http://status.infusionsoft.com",
		Name: "Infusionsoft by Keap",
	}, {
		URL:  "https://status.inlinemanual.com",
		Name: "Inline Manual",
	}, {
		URL:  "http://status.goinnovo.com",
		Name: "Innovo",
	}, {
		URL:  "https://status.inspectar.com",
		Name: "inspectAR",
	}, {
		URL:  "https://intuitdevelopergroup.statuspage.io",
		Name: "Intuit Developer",
	}, {
		URL:  "https://status.ionicframework.com",
		Name: "Ionic Framework",
	}, {
		URL:  "https://status.ipapi.com",
		Name: "Ipapi",
	}, {
		URL:  "https://status.jellyfish.co",
		Name: "Jellyfish",
	}, {
		URL:  "https://status.jetbrains.com",
		Name: "JetBrains",
	}, {
		URL:  "https://jexo.statuspage.io",
		Name: "Jexo",
	}, {
		URL:  "https://jira-align.status.atlassian.com",
		Name: "Jira Align",
	}, {
		URL:  "https://jira-product-discovery.status.atlassian.com",
		Name: "Jira Product Discovery",
	}, {
		URL:  "https://jira-service-management.status.atlassian.com",
		Name: "Jira Service Management",
	}, {
		URL:  "https://jira-work-management.status.atlassian.com",
		Name: "Jira Work Management",
	}, {
		URL:  "https://status.jitpack.io",
		Name: "JitPack",
	}, {
		URL:  "https://status.judoscale.com",
		Name: "Judoscale",
	}, {
		URL:  "https://status.keypup.io",
		Name: "Keypup",
	}, {
		URL:  "https://status.launchdarkly.com",
		Name: "LaunchDarkly",
	}, {
		URL:  "https://status.layer0.co",
		Name: "Layer0",
	}, {
		URL:  "https://status.leanix.net",
		Name: "LeanIX",
	}, {
		URL:  "https://status.licensespring.com",
		Name: "LicenseSpring",
	}, {
		URL:  "https://status.liferay.com",
		Name: "Liferay",
	}, {
		URL:  "https://status.lokalise.com",
		Name: "Lokalise",
	}, {
		URL:  "https://status.macstadium.com",
		Name: "MacStadium",
	}, {
		URL:  "https://developer.mastercard.com/api-status",
		Name: "Mastercard API",
	}, {
		URL:  "https://status.mendix.com",
		Name: "Mendix",
	}, {
		URL:  "https://status.meteor.com",
		Name: "Meteor",
	}, {
		URL:  "https://status.mezmo.com",
		Name: "Mezmo",
	}, {
		URL:  "https://status.mohami.io",
		Name: "Mohami",
	}, {
		URL:  "https://status.moveworks.com",
		Name: "Moveworks",
	}, {
		URL:  "https://status.ncr.com",
		Name: "NCR",
	}, {
		URL:  "https://status.ngrok.com",
		Name: "Ngrok",
	}, {
		URL:  "https://status.nightfall.ai",
		Name: "Nightfall",
	}, {
		URL:  "https://status.nowsta.com",
		Name: "Nowsta",
	}, {
		URL:  "https://status.npmjs.org",
		Name: "NPM",
	}, {
		URL:  "https://status.openai.com",
		Name: "OpenAI",
	}, {
		URL:  "https://status.otoy.com",
		Name: "OTOY",
	}, {
		URL:  "https://status.outsystems.com",
		Name: "Outsystems",
	}, {
		URL:  "http://www.packagecloudstatus.io",
		Name: "packagecloud",
	}, {
		URL:  "https://status.paperplane.app",
		Name: "Paperplane",
	}, {
		URL:  "https://status.pendo.io",
		Name: "Pendo",
	}, {
		URL:  "https://status.percy.io",
		Name: "Percy",
	}, {
		URL:  "https://permit-io.instatus.com",
		Name: "Permit-io",
	}, {
		URL:  "https://status.pgmustard.com",
		Name: "pgMustard",
	}, {
		URL:  "https://status.phantombuster.com",
		Name: "Phantombuster",
	}, {
		URL:  "https://status.pipedream.com",
		Name: "Pipedream",
	}, {
		URL:  "https://status.getpostman.com",
		Name: "Postman",
	}, {
		URL:  "https://status.prerender.io",
		Name: "Prerender.io",
	}, {
		URL:  "https://status.pricehubble.com",
		Name: "PriceHubble",
	}, {
		URL:  "https://status.prismic.io",
		Name: "Prismic",
	}, {
		URL:  "https://status.pullrequest.com",
		Name: "PullRequest",
	}, {
		URL:  "https://status.pulumi.com",
		Name: "Pulumi",
	}, {
		URL:  "https://status.pusher.com",
		Name: "Pusher",
	}, {
		URL:  "https://status.pushy.me",
		Name: "Pushy",
	}, {
		URL:  "https://status.python.org",
		Name: "Python Package Index",
	}, {
		URL:  "https://status.qovery.com",
		Name: "Qovery",
	}, {
		URL:  "https://service.quickbase.com",
		Name: "Quick Base",
	}, {
		URL:  "https://status.rapidapi.com",
		Name: "RapidAPI",
	}, {
		URL:  "https://status.carrerafuncionaria.cl",
		Name: "Raptor Systems",
	}, {
		URL:  "https://status.raygun.com",
		Name: "Raygun",
	}, {
		URL:  "https://www.readmestatus.com",
		Name: "Readme",
	}, {
		URL:  "https://status.redhat.com",
		Name: "Red Hat",
	}, {
		URL:  "https://status.replit.com",
		Name: "Replit",
	}, {
		URL:  "https://status.revenuecat.com",
		Name: "RevenueCat",
	}, {
		URL:  "http://status.rollbar.com",
		Name: "Rollbar",
	}, {
		URL:  "https://status.rookout.com",
		Name: "Rookout",
	}, {
		URL:  "https://status.rubygems.org",
		Name: "RubyGems",
	}, {
		URL:  "https://status.sanity.io",
		Name: "Sanity",
	}, {
		URL:  "https://status.sashido.io",
		Name: "SashiDo",
	}, {
		URL:  "https://status.saucelabs.com",
		Name: "Sauce Labs",
	}, {
		URL:  "https://status.scale.com",
		Name: "Scale AI",
	}, {
		URL:  "https://scraperapi.hund.io",
		Name: "Scraperapi",
	}, {
		URL:  "https://status.scrapingbee.com",
		Name: "ScrapingBee",
	}, {
		URL:  "http://status.semaphoreci.com",
		Name: "Semaphore",
	}, {
		URL:  "https://status.getsentry.com",
		Name: "Sentry",
	}, {
		URL:  "https://status.shortcut.com",
		Name: "Shortcut",
	}, {
		URL:  "https://status.sitespect.com",
		Name: "SiteSpect",
	}, {
		URL:  "https://sonarcloud.statuspage.io",
		Name: "SonarCloud",
	}, {
		URL:  "https://spacelift.statuspage.io",
		Name: "Spacelift",
	}, {
		URL:  "https://status.split.io",
		Name: "Split",
	}, {
		URL:  "https://status.stacker.app",
		Name: "Stacker",
	}, {
		URL:  "https://www.stackstatus.net",
		Name: "Stack Exchange",
	}, {
		URL:  "http://status.stoplight.io",
		Name: "StopLight",
	}, {
		URL:  "https://status.usesummit.com",
		Name: "Summit",
	}, {
		URL:  "https://surveymonkey.statuspage.io",
		Name: "SurveyMonkey",
	}, {
		URL:  "https://status.temporal.io",
		Name: "Temporal",
	}, {
		URL:  "https://status.tide.co",
		Name: "Tide",
	}, {
		URL:  "https://status.transbankdevelopers.cl",
		Name: "Transbank",
	}, {
		URL:  "https://www.traviscistatus.com",
		Name: "Travis CI",
	}, {
		URL:  "https://status.tray.io",
		Name: "Tray.io",
	}, {
		URL:  "https://status.tuple.app",
		Name: "Tuple",
	}, {
		URL:  "https://status.cloud.unity3d.com",
		Name: "Unity",
	}, {
		URL:  "https://status.visma.com",
		Name: "Visma",
	}, {
		URL:  "https://status.voxeet.com",
		Name: "Voxeet",
	}, {
		URL:  "https://status.appcenter.ms",
		Name: "VS App Center",
	}, {
		URL:  "http://status.waydev.co",
		Name: "WayDev",
	}, {
		URL:  "https://status.wpmudev.com",
		Name: "WPMU DEV",
	}, {
		URL:  "https://zenscrape.freshstatus.io",
		Name: "Zenscrape",
	}, {
		URL:  "https://status.zeplin.io",
		Name: "Zeplin",
	}, {
		URL:  "https://status.zyte.com",
		Name: "Zyte",
	}, {
		URL:  "https://status.csgostats.gg",
		Name: "CS:GO stats",
	}, {
		URL:  "",
		Name: "Fortnite",
	}, {
		URL:  "https://status.play.google.com",
		Name: "Google Play",
	}, {
		URL:  "https://status.g-portal.com",
		Name: "GPORTAL",
	}, {
		URL:  "https://status.hypixel.net",
		Name: "Hypixel",
	}, {
		URL:  "https://status.munzee.com",
		Name: "Munzee",
	}, {
		URL:  "https://status.geforcenow.com",
		Name: "NVIDIA GeForce",
	}, {
		URL:  "http://status.oneskyapp.com",
		Name: "OneSky",
	}, {
		URL:  "https://status.parsec.app",
		Name: "Parsec",
	}, {
		URL:  "https://status.playstation.com/data/statuses/region/SCEA.json",
		Name: "Playstation",
	}, {
		URL:  "https://status.roblox.com",
		Name: "Roblox",
	}, {
		URL:  "https://status.cloud.unity3d.com",
		Name: "Unity",
	}, {
		URL:  "https://status.unosial.com",
		Name: "Unosial",
	}, {
		URL:  "https://support.xbox.com/en-US/xbox-live-status",
		Name: "Xbox Live",
	}, {
		URL:  "https://stackstatus.com",
		Name: "20i",
	}, {
		URL:  "https://status.alphavps.com",
		Name: "AlphaVPS",
	}, {
		URL:  "https://anchorhost.statuspage.io",
		Name: "Anchor Host",
	}, {
		URL:  "http://status.binarylane.com.au",
		Name: "Binary Lane",
	}, {
		URL:  "https://status.catalystcloud.nz",
		Name: "Catalyst Cloud",
	}, {
		URL:  "http://status.cdc.systems",
		Name: "CDC Service",
	}, {
		URL:  "http://status.cloud66.com",
		Name: "Cloud 66",
	}, {
		URL:  "https://status.cloudamqp.com",
		Name: "CloudAMQP",
	}, {
		URL:  "https://status.cloudsigma.com",
		Name: "CloudSigma",
	}, {
		URL:  "https://status.codetwo.com",
		Name: "CodeTwo",
	}, {
		URL:  "https://status.combell.com/en",
		Name: "Combell",
	}, {
		URL:  "https://status.crucial.com.au",
		Name: "Crucial Hosting",
	}, {
		URL:  "https://dhostingstatus.com",
		Name: "Dhosting",
	}, {
		URL:  "https://status.digitalocean.com",
		Name: "DigitalOcean",
	}, {
		URL:  "https://dnsimple.statuspage.io",
		Name: "DNSimple",
	}, {
		URL:  "https://status.dogado.de",
		Name: "dogado",
	}, {
		URL:  "https://status.dongee.com",
		Name: "Dongee",
	}, {
		URL:  "https://www.dreamhoststatus.com",
		Name: "DreamHost",
	}, {
		URL:  "https://exoscalestatus.com",
		Name: "Exoscale",
	}, {
		URL:  "https://status.finalsite.com",
		Name: "Finalsite",
	}, {
		URL:  "https://status.getflywheel.com",
		Name: "Flywheel",
	}, {
		URL:  "https://status.fragnet.net",
		Name: "Fragnet Networks",
	}, {
		URL:  "https://status.freistilbox.com",
		Name: "freistilbox",
	}, {
		URL:  "https://gearhost.statuspage.io",
		Name: "GearHost",
	}, {
		URL:  "https://status.getresponse.com",
		Name: "GetResponse",
	}, {
		URL:  "https://status.gitlabhost.com",
		Name: "GitLabHost",
	}, {
		URL:  "https://www.godaddy.com/system-status",
		Name: "GoDaddy",
	}, {
		URL:  "https://status.hetzner.com",
		Name: "Hetzner",
	}, {
		URL:  "https://status.hostifi.com",
		Name: "HostiFi",
	}, {
		URL:  "https://statuspage.hostinger.com",
		Name: "Hostinger",
	}, {
		URL:  "https://www.hostpapastatus.com",
		Name: "HostPapa",
	}, {
		URL:  "https://status.hostpress.de",
		Name: "HostPress",
	}, {
		URL:  "https://status.hostry.com",
		Name: "Hostry",
	}, {
		URL:  "http://hoverstatus.com",
		Name: "Hover",
	}, {
		URL:  "https://www.hypernode-status.com",
		Name: "Hypernode",
	}, {
		URL:  "https://status.instaclustr.com",
		Name: "Instaclustr",
	}, {
		URL:  "https://status.iwantmyname.com",
		Name: "I Want My Name",
	}, {
		URL:  "https://status.kinsta.com",
		Name: "Kinsta",
	}, {
		URL:  "https://status.kualo.com",
		Name: "Kualo",
	}, {
		URL:  "https://status.latitude.sh",
		Name: "Latitude.sh",
	}, {
		URL:  "https://status.layerstack.com",
		Name: "LayerStack",
	}, {
		URL:  "https://status.linode.com",
		Name: "Linode",
	}, {
		URL:  "https://status.liquidweb.com",
		Name: "Liquid Web",
	}, {
		URL:  "https://status.lumaserv.com",
		Name: "LUMASERV",
	}, {
		URL:  "https://status.magemojo.com",
		Name: "MageMojo",
	}, {
		URL:  "https://status.moodle.com",
		Name: "Moodle",
	}, {
		URL:  "https://www.namecheap.com/status-updates",
		Name: "Namecheap",
	}, {
		URL:  "https://status.nestify.io/en",
		Name: "Nestify",
	}, {
		URL:  "https://status.nexcess.net",
		Name: "Nexcess",
	}, {
		URL:  "https://status.nhost.io",
		Name: "Nhost",
	}, {
		URL:  "https://status.noip.com",
		Name: "No-IP",
	}, {
		URL:  "https://status.one.com",
		Name: "One",
	}, {
		URL:  "https://status.us.ovhcloud.com",
		Name: "OVHcloud",
	}, {
		URL:  "https://status.pantheon.io",
		Name: "Pantheon",
	}, {
		URL:  "https://status.plox.host",
		Name: "PloxHost",
	}, {
		URL:  "https://status.plusserver.com",
		Name: "PlusServer",
	}, {
		URL:  "https://status.presslabs.com",
		Name: "Presslabs",
	}, {
		URL:  "https://status.quadranet.com",
		Name: "QuadraNet",
	}, {
		URL:  "https://status.register.it",
		Name: "Register.it",
	}, {
		URL:  "https://status.rocket.net",
		Name: "Rocket.net",
	}, {
		URL:  "https://status.section.io",
		Name: "Section",
	}, {
		URL:  "https://status.seravo.com",
		Name: "Seravo",
	}, {
		URL:  "https://serveboltstatus.com",
		Name: "Servebolt",
	}, {
		URL:  "https://status.mysau.com.au",
		Name: "Servers Australia",
	}, {
		URL:  "https://status.shockbyte.com",
		Name: "Shockbyte",
	}, {
		URL:  "https://status.shockhosting.net",
		Name: "Shock Hosting",
	}, {
		URL:  "https://status.uk2.net",
		Name: "UK2",
	}, {
		URL:  "https://status.ultradns.com",
		Name: "UltraDNS",
	}, {
		URL:  "https://status.umbrellar.com",
		Name: "Umbrellar",
	}, {
		URL:  "https://status.united-hoster.de",
		Name: "United Hoster GmbH",
	}, {
		URL:  "https://status.velocityhost.com.au",
		Name: "Velocity Host",
	}, {
		URL:  "https://status.vpsserver.com",
		Name: "VPSServer",
	}, {
		URL:  "https://status.vultr.com",
		Name: "Vultr",
	}, {
		URL:  "https://status.webcentral.au",
		Name: "Webcentral",
	}, {
		URL:  "https://www.wikimediastatus.net",
		Name: "Wikimedia",
	}, {
		URL:  "https://status.wix.com",
		Name: "Wix",
	}, {
		URL:  "https://wpenginestatus.com",
		Name: "WP Engine",
	}, {
		URL:  "https://status.wpmudev.com",
		Name: "WPMU DEV",
	}, {
		URL:  "https://status.3stepit.com",
		Name: "3stepIT",
	}, {
		URL:  "https://status.8base.com",
		Name: "8base",
	}, {
		URL:  "https://status.ada.support",
		Name: "Ada",
	}, {
		URL:  "https://status.addigy.com",
		Name: "Addigy",
	}, {
		URL:  "https://edgedns.status.akamai.com",
		Name: "Akamai Edge DNS",
	}, {
		URL:  "https://status.alloy.com",
		Name: "Alloy",
	}, {
		URL:  "https://www.amplifiedit.com/status",
		Name: "Amplified IT",
	}, {
		URL:  "https://status.apify.com",
		Name: "Apify",
	}, {
		URL:  "https://apwide.statuspage.io",
		Name: "Apwide",
	}, {
		URL:  "https://status.assembled.com",
		Name: "Assembled",
	}, {
		URL:  "https://status.atera.com",
		Name: "Atera",
	}, {
		URL:  "https://status.atlassian.com",
		Name: "Atlassian",
	}, {
		URL:  "https://status.askspoke.com",
		Name: "atSpoke",
	}, {
		URL:  "https://status.autospf.com",
		Name: "AutoSPF",
	}, {
		URL:  "https://status.auvik.com",
		Name: "Auvik",
	}, {
		URL:  "https://status.avanan.com",
		Name: "Avanan",
	}, {
		URL:  "https://status.bettercloud.com",
		Name: "BetterCloud",
	}, {
		URL:  "https://status.bitly.com",
		Name: "Bitly",
	}, {
		URL:  "https://status.bittitan.com",
		Name: "BitTitan",
	}, {
		URL:  "https://status.bossdesk.io",
		Name: "BOSSDesk",
	}, {
		URL:  "https://status.brave.com",
		Name: "Brave",
	}, {
		URL:  "https://status.brightlysoftware.com",
		Name: "Brightly Software",
	}, {
		URL:  "https://status.canonical.com",
		Name: "Canonical",
	}, {
		URL:  "https://status.carrotquest.io",
		Name: "Carrot quest",
	}, {
		URL:  "https://status.catonetworks.com",
		Name: "Cato Networks",
	}, {
		URL:  "https://status.cherwellondemand.com",
		Name: "Cherwell",
	}, {
		URL:  "https://status.ces.cisco.com",
		Name: "Cisco CES",
	}, {
		URL:  "https://status.meraki.net",
		Name: "Cisco Meraki",
	}, {
		URL:  "https://status.cloudamqp.com",
		Name: "CloudAMQP",
	}, {
		URL:  "https://www.cloudbeesstatus.com",
		Name: "CloudBees",
	}, {
		URL:  "https://status.cloudradial.net",
		Name: "CloudRadial",
	}, {
		URL:  "https://status.joinclyde.com",
		Name: "Clyde",
	}, {
		URL:  "https://status.cocoapods.org",
		Name: "CocoaPods",
	}, {
		URL:  "http://status.codewars.com",
		Name: "Codewars",
	}, {
		URL:  "https://www.colt.net/status",
		Name: "Colt",
	}, {
		URL:  "https://status.comptia.net",
		Name: "CompTIA",
	}, {
		URL:  "https://status.connectwise.com",
		Name: "ConnectWise",
	}, {
		URL:  "https://status.cradlepoint.com",
		Name: "Cradlepoint",
	}, {
		URL:  "http://status.cumulocity.com",
		Name: "Cumulocity",
	}, {
		URL:  "https://datacake-status.com",
		Name: "Datacake",
	}, {
		URL:  "https://status.datto.com",
		Name: "Datto",
	}, {
		URL:  "https://www.deskprostatus.com",
		Name: "Deskpro",
	}, {
		URL:  "http://status.devolutions.net",
		Name: "Devolutions",
	}, {
		URL:  "https://status.dixa.io",
		Name: "Dixa",
	}, {
		URL:  "https://status.docebo.com",
		Name: "Docebo",
	}, {
		URL:  "https://status.easyredir.com",
		Name: "EasyRedir",
	}, {
		URL:  "https://elation.status.io",
		Name: "Elation Health",
	}, {
		URL:  "https://status.elev.io",
		Name: "Elevio",
	}, {
		URL:  "https://stats.uptimerobot.com/VkNVYS2vV6",
		Name: "EPS - Internet Connections",
	}, {
		URL:  "https://status.esa.io",
		Name: "esa",
	}, {
		URL:  "http://exa.freshstatus.io",
		Name: "Exa",
	}, {
		URL:  "https://status.exalate.com",
		Name: "Exalate",
	}, {
		URL:  "https://cloud-status.extremecloudiq.com/status/index.html",
		Name: "Extreme Networks",
	}, {
		URL:  "https://status.fingerprintjs.com",
		Name: "FingerprintJS",
	}, {
		URL:  "https://flagsmith.statuspage.io",
		Name: "FlagSmith",
	}, {
		URL:  "https://status.flexera.com",
		Name: "Flexera",
	}, {
		URL:  "https://status.flying-sphinx.com",
		Name: "Flying Sphinx",
	}, {
		URL:  "http://status.fond.co",
		Name: "Fond",
	}, {
		URL:  "https://status.formspree.io",
		Name: "Formspree",
	}, {
		URL:  "https://status.freee.co.jp",
		Name: "Freee",
	}, {
		URL:  "https://updates.freshservice.com",
		Name: "Freshservice",
	}, {
		URL:  "https://status.frigade.com",
		Name: "Frigade",
	}, {
		URL:  "https://status.frontegg.com",
		Name: "Frontegg",
	}, {
		URL:  "https://status.g2.com",
		Name: "G2",
	}, {
		URL:  "https://status.gainsight.com",
		Name: "Gainsight",
	}, {
		URL:  "https://geckoboard.statuspage.io",
		Name: "Geckoboard",
	}, {
		URL:  "https://status.geekbot.com",
		Name: "Geekbot",
	}, {
		URL:  "https://gladly.statuspage.io",
		Name: "Gladly",
	}, {
		URL:  "https://status.glideapps.com",
		Name: "Glide apps",
	}, {
		URL:  "https://status.helloglobo.com",
		Name: "GLOBO",
	}, {
		URL:  "https://status.golinks.io",
		Name: "GoLinks",
	}, {
		URL:  "https://status.goodtime.io",
		Name: "GoodTime",
	}, {
		URL:  "http://status.logmeinaccess.com",
		Name: "GoToMyPC",
	}, {
		URL:  "http://stats.pingdom.com/xf7vwkfqygcb",
		Name: "Gremlin",
	}, {
		URL:  "https://status.groovehq.com",
		Name: "Groove",
	}, {
		URL:  "https://status.hackerrank.com",
		Name: "HackerRank",
	}, {
		URL:  "https://status.halp.com",
		Name: "Halp",
	}, {
		URL:  "https://status.hashnode.com",
		Name: "Hashnode",
	}, {
		URL:  "https://status.hasura.io",
		Name: "Hasura",
	}, {
		URL:  "https://status.hearsaysystems.com",
		Name: "Hearsay Systems",
	}, {
		URL:  "https://status.helpdesk.com",
		Name: "HelpDesk",
	}, {
		URL:  "https://status.helpjuice.com",
		Name: "Helpjuice",
	}, {
		URL:  "https://status.helpscout.com",
		Name: "HelpScout",
	}, {
		URL:  "https://status.helpshift.com",
		Name: "Helpshift",
	}, {
		URL:  "https://status.herocoders.com",
		Name: "HeroCoders",
	}, {
		URL:  "https://status.highspot.com",
		Name: "Highspot",
	}, {
		URL:  "https://status.hive.com",
		Name: "Hive",
	}, {
		URL:  "https://status.iboss.com/ibcloud/app/cloudStatus.html",
		Name: "iboss",
	}, {
		URL:  "https://www.icewarp.de/en/support/service-status/#:~:text=Dec%2001%2C%202022%20No%20incidents%20reported%20today.",
		Name: "IceWarp",
	}, {
		URL:  "https://status.inriver.com",
		Name: "Innovo",
	}, {
		URL:  "https://status.inriver.com",
		Name: "Inriver",
	}, {
		URL:  "https://status.inspectar.com",
		Name: "inspectAR",
	}, {
		URL:  "https://status.instride.com",
		Name: "InStride",
	}, {
		URL:  "https://intuitdevelopergroup.statuspage.io",
		Name: "Intuit Developer",
	}, {
		URL:  "https://status.ipapi.com",
		Name: "Ipapi",
	}, {
		URL:  "https://status.itglue.com",
		Name: "ITGlue",
	}, {
		URL:  "https://itportal1.statuspage.io",
		Name: "IT Portal",
	}, {
		URL:  "https://status.jamf.com",
		Name: "Jamf",
	}, {
		URL:  "https://status.jellyfish.co",
		Name: "Jellyfish",
	}, {
		URL:  "https://status.jenkins.io",
		Name: "Jenkins",
	}, {
		URL:  "https://statuspage.jitbit.com",
		Name: "JitBit",
	}, {
		URL:  "https://status.jitpack.io",
		Name: "JitPack",
	}, {
		URL:  "https://status.judoscale.com",
		Name: "Judoscale",
	}, {
		URL:  "https://status.kaseya.net",
		Name: "Kaseya",
	}, {
		URL:  "https://status.keeping.com",
		Name: "Keeping",
	}, {
		URL:  "https://status.keypup.io",
		Name: "Keypup",
	}, {
		URL:  "https://status.launchdarkly.com",
		Name: "LaunchDarkly",
	}, {
		URL:  "https://status.launchnotes.com",
		Name: "LaunchNotes",
	}, {
		URL:  "https://status.layer0.co",
		Name: "Layer0",
	}, {
		URL:  "https://status.leanix.net",
		Name: "LeanIX",
	}, {
		URL:  "https://status.licensespring.com",
		Name: "LicenseSpring",
	}, {
		URL:  "https://status.liferay.com",
		Name: "Liferay",
	}, {
		URL:  "https://status.logmeinaccess.com",
		Name: "LogMeIn Pro",
	}, {
		URL:  "https://status.logmeinremotesupport.com",
		Name: "LogMeIn Rescue",
	}, {
		URL:  "http://status.lookback.io",
		Name: "Lookback",
	}, {
		URL:  "https://status.loyaltylion.com",
		Name: "LoyaltyLion",
	}, {
		URL:  "https://status.maestroqa.com",
		Name: "MaestroQA",
	}, {
		URL:  "http://magensa.statuspage.io",
		Name: "Magensa",
	}, {
		URL:  "https://status.make.com",
		Name: "Make",
	}, {
		URL:  "https://status.manageengine.com",
		Name: "ManageEngine",
	}, {
		URL:  "https://status.maxmind.com",
		Name: "MaxMind",
	}, {
		URL:  "https://status.mealmagic.com",
		Name: "Meal Magic",
	}, {
		URL:  "http://status.meridiankiosks.com",
		Name: "Meridian",
	}, {
		URL:  "https://status.meridianlink.com",
		Name: "MeridianLink",
	}, {
		URL:  "https://status.meteor.com",
		Name: "Meteor",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft 365 apps",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft 365 for the web",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft 365 suite",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft Forms",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft Power Automate in Microsoft 365",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft Stream",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft Viva",
	}, {
		URL:  "https://mojohelpdesk.montastic.io",
		Name: "Mojo Helpdesk",
	}, {
		URL:  "https://status.moveworks.com",
		Name: "Moveworks",
	}, {
		URL:  "https://uptime.n-able.com",
		Name: "N-able",
	}, {
		URL:  "https://status.narvar.com",
		Name: "Narvar",
	}, {
		URL:  "https://status.ncr.com",
		Name: "NCR",
	}, {
		URL:  "https://status.ninety.io",
		Name: "Ninety",
	}, {
		URL:  "https://status.nowsta.com",
		Name: "Nowsta",
	}, {
		URL:  "https://status.nutshell.com",
		Name: "Nutshell",
	}, {
		URL:  "https://status.ocrolus.com",
		Name: "Ocrolus",
	}, {
		URL:  "https://status.officernd.com",
		Name: "OfficeRnD",
	}, {
		URL:  "https://status.oneschema.co",
		Name: "OneSchema",
	}, {
		URL:  "https://status.opencagedata.com",
		Name: "OpenCage",
	}, {
		URL:  "https://www.orttostatus.com",
		Name: "Ortto",
	}, {
		URL:  "https://status.otoy.com",
		Name: "OTOY",
	}, {
		URL:  "https://status.pairsoft.com",
		Name: "PairSoft",
	}, {
		URL:  "https://status.particle.io",
		Name: "Particle",
	}, {
		URL:  "https://status.patchmypc.com",
		Name: "Patch My PC",
	}, {
		URL:  "https://status.pax8.com",
		Name: "Pax8",
	}, {
		URL:  "https://status.people.ai",
		Name: "People.ai",
	}, {
		URL:  "https://status.percy.io",
		Name: "Percy",
	}, {
		URL:  "https://permit-io.instatus.com",
		Name: "Permit-io",
	}, {
		URL:  "https://status.pipedream.com",
		Name: "Pipedream",
	}, {
		URL:  "https://status.podio.com",
		Name: "Podio",
	}, {
		URL:  "https://status.polly.ai",
		Name: "Polly",
	}, {
		URL:  "https://status.office365.com",
		Name: "Power Apps in Microsoft 365",
	}, {
		URL:  "https://status.preyproject.com",
		Name: "Prey",
	}, {
		URL:  "https://status.printercloud.com",
		Name: "PrinterLogic",
	}, {
		URL:  "https://status.project44.com",
		Name: "Project44",
	}, {
		URL:  "https://status.prosperstack.com",
		Name: "ProsperStack",
	}, {
		URL:  "https://status.pullrequest.com",
		Name: "PullRequest",
	}, {
		URL:  "https://status.pureservice.com",
		Name: "Pureservice",
	}, {
		URL:  "https://status.pushy.me",
		Name: "Pushy",
	}, {
		URL:  "https://status.qovery.com",
		Name: "Qovery",
	}, {
		URL:  "https://status.qualys.com",
		Name: "Qualys",
	}, {
		URL:  "https://status.recruiterbox.com",
		Name: "Recruiterbox",
	}, {
		URL:  "https://status.redhat.com",
		Name: "Red Hat",
	}, {
		URL:  "https://status.reftab.com",
		Name: "Reftab",
	}, {
		URL:  "https://status.revenuecat.com",
		Name: "RevenueCat",
	}, {
		URL:  "https://status.roadmunk.com",
		Name: "Roadmunk",
	}, {
		URL:  "https://status.roboyo.global",
		Name: "Roboyo",
	}, {
		URL:  "https://status.rootly.com",
		Name: "Rootly",
	}, {
		URL:  "https://status.samanage.com",
		Name: "Samanage",
	}, {
		URL:  "https://sapling.statuspage.io",
		Name: "Sapling",
	}, {
		URL:  "https://scraperapi.hund.io",
		Name: "Scraperapi",
	}, {
		URL:  "https://sectigo.status.io",
		Name: "Sectigo",
	}, {
		URL:  "https://status.securew2.com",
		Name: "SecureW2",
	}, {
		URL:  "https://status.securityscorecard.com",
		Name: "SecurityScorecard",
	}, {
		URL:  "http://status.senso.cloud",
		Name: "Senso",
	}, {
		URL:  "https://status.shakebugs.com",
		Name: "ShakeBugs",
	}, {
		URL:  "https://app-status.sharegate.com",
		Name: "ShareGate",
	}, {
		URL:  "https://status.shelf.io",
		Name: "Shelf.io",
	}, {
		URL:  "https://slabstatus.com",
		Name: "Slab",
	}, {
		URL:  "https://status.slido.com",
		Name: "Slido",
	}, {
		URL:  "https://status.sonicwall.com",
		Name: "SonicWall",
	}, {
		URL:  "https://spacelift.statuspage.io",
		Name: "Spacelift",
	}, {
		URL:  "https://speakap.statuspage.io",
		Name: "Speakap",
	}, {
		URL:  "http://status.splashtop.com",
		Name: "Splashtop",
	}, {
		URL:  "https://status.squiz.cloud",
		Name: "Squiz",
	}, {
		URL:  "https://status.usesummit.com",
		Name: "Summit",
	}, {
		URL:  "http://status.us2.sumologic.com",
		Name: "Sumo Logic US2",
	}, {
		URL:  "https://status.swaggerhub.com",
		Name: "Swagger",
	}, {
		URL:  "https://status.sysaid.com",
		Name: "SysAid",
	}, {
		URL:  "https://teamretro.betteruptime.com",
		Name: "TeamRetro",
	}, {
		URL:  "http://status.teamsupport.com",
		Name: "TeamSupport",
	}, {
		URL:  "https://status.teamviewer.com",
		Name: "TeamViewer",
	}, {
		URL:  "https://status.temporal.io",
		Name: "Temporal",
	}, {
		URL:  "https://status.testmo.com",
		Name: "Testmo",
	}, {
		URL:  "https://testrail.statuspage.io",
		Name: "TestRail",
	}, {
		URL:  "https://status.threatx.com",
		Name: "ThreatX",
	}, {
		URL:  "http://status.ticketinghub.com",
		Name: "TicketingHub",
	}, {
		URL:  "https://status.tide.co",
		Name: "Tide",
	}, {
		URL:  "https://status.tidio.com",
		Name: "Tidio",
	}, {
		URL:  "https://status.tcpsoftware.com",
		Name: "TimeClock Plus",
	}, {
		URL:  "https://status.totango.com",
		Name: "Totango",
	}, {
		URL:  "https://tpxcommunications.statuspage.io",
		Name: "TPx Communications",
	}, {
		URL:  "https://status.trengo.com",
		Name: "Trengo",
	}, {
		URL:  "https://status.tyk.io",
		Name: "Tyk",
	}, {
		URL:  "https://status.ui.com",
		Name: "Ubiquiti",
	}, {
		URL:  "http://status.ujet.co",
		Name: "UJET",
	}, {
		URL:  "https://status.visma.com",
		Name: "Visma",
	}, {
		URL:  "https://vcc.statuspage.io",
		Name: "Vonage",
	}, {
		URL:  "https://vonageapi.statuspage.io",
		Name: "Vonage API",
	}, {
		URL:  "https://businesssupport.vonage.com/trust",
		Name: "Vonage Business",
	}, {
		URL:  "https://status.voyado.com",
		Name: "Voyado",
	}, {
		URL:  "https://status.webscrapingapi.com",
		Name: "WebScrapingAPI",
	}, {
		URL:  "https://status.whimsical.com",
		Name: "Whimsical",
	}, {
		URL:  "https://wpvipstatus.com",
		Name: "WordPress VIP",
	}, {
		URL:  "https://status.workato.com",
		Name: "Workato",
	}, {
		URL:  "https://status.workspot.com",
		Name: "Workspot",
	}, {
		URL:  "https://status.wpmudev.com",
		Name: "WPMU DEV",
	}, {
		URL:  "https://creditplus.com/system-status",
		Name: "Xactus",
	}, {
		URL:  "https://status.xmatters.com",
		Name: "xMatters",
	}, {
		URL:  "http://status.zenduty.com",
		Name: "Zenduty",
	}, {
		URL:  "https://zenscrape.freshstatus.io",
		Name: "Zenscrape",
	}, {
		URL:  "https://status.zenvia.com",
		Name: "Zenvia",
	}, {
		URL:  "https://status.zingle.me",
		Name: "Zingle",
	}, {
		URL:  "https://status.appriver.com",
		Name: "AppRiver",
	}, {
		URL:  "https://partners.status.atlassian.com",
		Name: "Atlassian Partners",
	}, {
		URL:  "https://support.status.atlassian.com",
		Name: "Atlassian Support",
	}, {
		URL:  "https://status.bigleaf.net",
		Name: "BigLeaf",
	}, {
		URL:  "https://bluebeam.hund.io",
		Name: "Bluebeam",
	}, {
		URL:  "https://status.box.com",
		Name: "Box",
	}, {
		URL:  "http://status.clickup.com",
		Name: "ClickUp",
	}, {
		URL:  "https://status.codetwo.com",
		Name: "CodeTwo",
	}, {
		URL:  "https://status.acats.com",
		Name: "ComplianceAlpha",
	}, {
		URL:  "https://dakboard.statuspal.io",
		Name: "DAKboard",
	}, {
		URL:  "https://status.documo.com",
		Name: "Documo",
	}, {
		URL:  "https://uptime.doodle.com",
		Name: "Doodle",
	}, {
		URL:  "https://status.dropbox.com",
		Name: "Dropbox",
	}, {
		URL:  "http://status.formstack.com",
		Name: "Formstack",
	}, {
		URL:  "https://status.gimlet.us",
		Name: "Gimlet",
	}, {
		URL:  "https://www.gitbookstatus.com",
		Name: "GitBook",
	}, {
		URL:  "https://www.google.com/appsstatus/dashboard",
		Name: "Google Workspace",
	}, {
		URL:  "https://status.gradle.com",
		Name: "Gradle",
	}, {
		URL:  "https://status.getguru.com",
		Name: "Guru",
	}, {
		URL:  "https://status.hiverhq.com",
		Name: "Hiver",
	}, {
		URL:  "http://status.liquidplanner.com",
		Name: "LiquidPlanner",
	}, {
		URL:  "https://lucidsoftware.statuspage.io",
		Name: "Lucidchart",
	}, {
		URL:  "https://status.matillion.com",
		Name: "Matillion",
	}, {
		URL:  "https://status.maze.co",
		Name: "Maze",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft Power Automate in Microsoft 365",
	}, {
		URL:  "https://status.office365.com",
		Name: "Microsoft Viva",
	}, {
		URL:  "https://status.milanote.com",
		Name: "Milanote",
	}, {
		URL:  "https://status.miro.com",
		Name: "Miro",
	}, {
		URL:  "https://status.monday.com",
		Name: "Monday",
	}, {
		URL:  "https://status.mural.co",
		Name: "Mural",
	}, {
		URL:  "https://trust-au.netdocuments.com",
		Name: "NetDocuments AU",
	}, {
		URL:  "https://trust-us.netdocuments.com",
		Name: "NetDocuments US",
	}, {
		URL:  "https://status.gonitro.com",
		Name: "Nitro",
	}, {
		URL:  "https://status.nokotime.com",
		Name: "Noko",
	}, {
		URL:  "https://status.nylas.com",
		Name: "Nylas",
	}, {
		URL:  "https://status.pinpoint.support",
		Name: "Pinpoint",
	}, {
		URL:  "https://status.pipefy.com",
		Name: "Pipefy",
	}, {
		URL:  "https://status.plangrid.com",
		Name: "PlanGrid",
	}, {
		URL:  "https://status.planview.com",
		Name: "Planview",
	}, {
		URL:  "https://status.prezi.com",
		Name: "Prezi",
	}, {
		URL:  "https://status.proofhub.com",
		Name: "ProofHub",
	}, {
		URL:  "https://realvnc.statuspage.io",
		Name: "RealVNC",
	}, {
		URL:  "https://status.reflektive.com",
		Name: "Reflektive",
	}, {
		URL:  "https://status.rescuetime.com",
		Name: "RescueTime",
	}, {
		URL:  "https://www.sap.com/uk/about/trust-center/cloud-service-status.html",
		Name: "SAP",
	}, {
		URL:  "https://savvycal.instatus.com",
		Name: "SavvyCal",
	}, {
		URL:  "https://status.secomea.com",
		Name: "Secomea",
	}, {
		URL:  "https://status.skedulo.com",
		Name: "Skedulo",
	}, {
		URL:  "https://smartpass.instatus.com",
		Name: "SmartPass",
	}, {
		URL:  "https://status.smartsheet.com",
		Name: "Smartsheet",
	}, {
		URL:  "https://teamretro.betteruptime.com",
		Name: "TeamRetro",
	}, {
		URL:  "https://status.teamwork.com",
		Name: "Teamwork",
	}, {
		URL:  "https://tettra.statuspage.io",
		Name: "Tettra",
	}, {
		URL:  "http://status.textexpander.com",
		Name: "TextExpander",
	}, {
		URL:  "https://status.tcpsoftware.com",
		Name: "TimeClock Plus",
	}, {
		URL:  "https://status.todoist.net",
		Name: "Todoist",
	}, {
		URL:  "https://status.tresorit.com",
		Name: "Tresorit",
	}, {
		URL:  "https://status.viapeople.net",
		Name: "viaPeople",
	}, {
		URL:  "https://status.webex.com/service/status",
		Name: "WebEx",
	}, {
		URL:  "https://status.wordtune.com",
		Name: "Wordtune",
	}, {
		URL:  "https://status.workflowy.com",
		Name: "WorkFlowy",
	}, {
		URL:  "https://1password.statuspage.io",
		Name: "1Password",
	}, {
		URL:  "http://status.3ncrypt3d.com",
		Name: "3NCRYPT3D",
	}, {
		URL:  "https://abnormalsecurity.statuspage.io",
		Name: "Abnormal Security",
	}, {
		URL:  "https://status.abuseipdb.com",
		Name: "AbuseIPDB",
	}, {
		URL:  "https://edgedns.status.akamai.com",
		Name: "Akamai Edge DNS",
	}, {
		URL:  "https://status.alertlogic.com",
		Name: "Alert Logic",
	}, {
		URL:  "https://status.alienvault.cloud",
		Name: "AlienVault",
	}, {
		URL:  "https://status.aptible.com",
		Name: "Aptible",
	}, {
		URL:  "https://status.area1security.com",
		Name: "Area 1",
	}, {
		URL:  "https://status.armor.com",
		Name: "Armor",
	}, {
		URL:  "https://access.status.atlassian.com",
		Name: "Atlassian Access",
	}, {
		URL:  "https://status.auth0.com",
		Name: "Auth0",
	}, {
		URL:  "https://status.authentic8.com",
		Name: "Authentic8",
	}, {
		URL:  "https://status.automox.com",
		Name: "Automox",
	}, {
		URL:  "https://status.avanan.com",
		Name: "Avanan",
	}, {
		URL:  "https://status.cloudcare.avg.com",
		Name: "Avast",
	}, {
		URL:  "https://status.openpath.com",
		Name: "Avigilon",
	}, {
		URL:  "https://status.axis.com",
		Name: "Axis Communications",
	}, {
		URL:  "https://status.barracuda.com",
		Name: "Barracuda",
	}, {
		URL:  "https://mwrmm.statuspage.io",
		Name: "Barracuda MSP",
	}, {
		URL:  "https://ssems.gravityzone.bitdefender.com",
		Name: "Bitdefender",
	}, {
		URL:  "https://status.blip.ai",
		Name: "Blip",
	}, {
		URL:  "https://status.bluefin.com",
		Name: "Bluefin",
	}, {
		URL:  "https://status.breachsecurenow.com",
		Name: "Breach Secure Now!",
	}, {
		URL:  "https://www.bugcrowdstatus.com",
		Name: "Bugcrowd",
	}, {
		URL:  "https://canary.statuspage.io",
		Name: "Canary",
	}, {
		URL:  "https://status.carbonblack.com",
		Name: "Carbon Black",
	}, {
		URL:  "https://status.castle.io",
		Name: "Castle",
	}, {
		URL:  "https://status.checkpoint.com",
		Name: "Check Point",
	}, {
		URL:  "https://status.ces.cisco.com",
		Name: "Cisco CES",
	}, {
		URL:  "https://status.umbrella.com",
		Name: "Cisco Umbrella",
	}, {
		URL:  "https://status.code42.com",
		Name: "Code 42",
	}, {
		URL:  "https://www.colt.net/status",
		Name: "Colt",
	}, {
		URL:  "https://status.one.comodo.com",
		Name: "Comodo",
	}, {
		URL:  "https://trust.idaptive.com",
		Name: "CyberArk Software",
	}, {
		URL:  "https://status.cybersmart.co.uk",
		Name: "CyberSmart",
	}, {
		URL:  "https://status.cycode.com",
		Name: "Cycode",
	}, {
		URL:  "https://status.dashlane.com",
		Name: "Dashlane",
	}, {
		URL:  "https://status.datadome.co",
		Name: "DataDome",
	}, {
		URL:  "https://status.datagrail.io",
		Name: "DataGrail",
	}, {
		URL:  "https://status.deepsource.io",
		Name: "DeepSource",
	}, {
		URL:  "https://status.digicert.com",
		Name: "DigiCert",
	}, {
		URL:  "https://status.dnsfilter.com",
		Name: "DNSFilter",
	}, {
		URL:  "https://dratastatus.com",
		Name: "Drata",
	}, {
		URL:  "https://status.duo.com",
		Name: "Duo Security",
	}, {
		URL:  "https://www.dynstatus.com",
		Name: "Dyn",
	}, {
		URL:  "https://ukstatus.ek.co",
		Name: "Ekco",
	}, {
		URL:  "https://status.eset.com",
		Name: "ESET",
	}, {
		URL:  "https://expeditedsecurity.statuspage.io",
		Name: "Expedited Security",
	}, {
		URL:  "https://status.expel.io",
		Name: "Expel",
	}, {
		URL:  "https://www.f5cloudstatus.com",
		Name: "F5",
	}, {
		URL:  "https://status.fingerprintjs.com",
		Name: "FingerprintJS",
	}, {
		URL:  "https://status.forcepoint.com/#/status/1",
		Name: "Forcepoint",
	}, {
		URL:  "https://csg.status.forcepoint.com",
		Name: "Forcepoint ONE",
	}, {
		URL:  "https://status.fossa.com",
		Name: "FOSSA",
	}, {
		URL:  "https://status.foxpass.com",
		Name: "Foxpass",
	}, {
		URL:  "https://status.f-secure.com",
		Name: "F-Secure",
	}, {
		URL:  "https://status.genetec.com",
		Name: "Genetec",
	}, {
		URL:  "https://gitguardian.statuspage.io",
		Name: "GitGuardian",
	}, {
		URL:  "https://status.greynoise.io",
		Name: "GreyNoise",
	}, {
		URL:  "https://guardrailsio.statuspage.io",
		Name: "GuardRails",
	}, {
		URL:  "https://www.hackeronestatus.com",
		Name: "HackerOne",
	}, {
		URL:  "https://status.hashicorp.com",
		Name: "HashiCorp",
	}, {
		URL:  "https://www.hcaptchastatus.com",
		Name: "hCaptcha",
	}, {
		URL:  "https://status.hdeone.com",
		Name: "HENNGE One",
	}, {
		URL:  "https://status.hornetsecurity.com",
		Name: "Hornetsecurity",
	}, {
		URL:  "https://huntressstatus.statuspage.io",
		Name: "Huntress",
	}, {
		URL:  "https://status.hyonix.com",
		Name: "Hyonix",
	}, {
		URL:  "https://statuspage.ibmcloudsecurity.com",
		Name: "IBM Security",
	}, {
		URL:  "https://status.imperva.com",
		Name: "Imperva",
	}, {
		URL:  "https://status.incapsula.com",
		Name: "Incapsula",
	}, {
		URL:  "https://status.incognia.com",
		Name: "Incognia",
	}, {
		URL:  "https://status.infoblox.com",
		Name: "Infoblox",
	}, {
		URL:  "https://status.inkyphishfence.com",
		Name: "INKY",
	}, {
		URL:  "https://status.intruder.io",
		Name: "Intruder",
	}, {
		URL:  "https://status.ipdata.co",
		Name: "ipdata",
	}, {
		URL:  "https://stats.uptimerobot.com/M90zYt5gGx",
		Name: "Ipregistry",
	}, {
		URL:  "https://ipvanish.statuspage.io",
		Name: "IPVanish",
	}, {
		URL:  "https://status.ironscales.com",
		Name: "IRONSCALES",
	}, {
		URL:  "https://statuspage.keeper.io",
		Name: "Keeper",
	}, {
		URL:  "https://status.kennasecurity.com",
		Name: "Kenna Security",
	}, {
		URL:  "https://status.kisi.io",
		Name: "Kisi",
	}, {
		URL:  "https://status.knowbe4.com",
		Name: "KnowBe4",
	}, {
		URL:  "https://status.kolide.com",
		Name: "Kolide",
	}, {
		URL:  "https://status.lastpass.com",
		Name: "LastPass",
	}, {
		URL:  "https://status.latch.com",
		Name: "Latch",
	}, {
		URL:  "https://status.ledger.com",
		Name: "Ledger",
	}, {
		URL:  "https://letsencrypt.status.io",
		Name: "Let's Encrypt",
	}, {
		URL:  "https://status.luxsci.com",
		Name: "LuxSci",
	}, {
		URL:  "https://status.maxmind.com",
		Name: "MaxMind",
	}, {
		URL:  "https://status.mimecast.com",
		Name: "Mimecast",
	}, {
		URL:  "https://status.mnemonichq.com",
		Name: "Mnemonic",
	}, {
		URL:  "https://mxtoolbox.statuspage.io",
		Name: "MxToolbox",
	}, {
		URL:  "https://status.nordlayer.com",
		Name: "NordLayer",
	}, {
		URL:  "https://nudgesecurity.statuspage.io",
		Name: "Nudge Security",
	}, {
		URL:  "https://status.obsidiansecurity.com",
		Name: "Obsidian Security",
	}, {
		URL:  "https://trust.opswat.com",
		Name: "OPSWAT",
	}, {
		URL:  "https://saasstatus.oracle.com",
		Name: "Oracle Trust Center",
	}, {
		URL:  "https://status.paloaltonetworks.com",
		Name: "Palo Alto Networks",
	}, {
		URL:  "https://status.panther.com",
		Name: "Panther Labs",
	}, {
		URL:  "https://status.parchment.com",
		Name: "Parchment",
	}, {
		URL:  "https://status.perimeter81.com",
		Name: "Perimeter 81",
	}, {
		URL:  "https://uptime.proctorio.com",
		Name: "Proctorio",
	}, {
		URL:  "https://status.protecht.io",
		Name: "Protecht",
	}, {
		URL:  "https://status.proxyclick.com",
		Name: "Proxyclick",
	}, {
		URL:  "https://status.pushsecurity.com",
		Name: "Push Security",
	}, {
		URL:  "https://status.qualys.com",
		Name: "Qualys",
	}, {
		URL:  "https://cwaf.status.radwarecloud.com",
		Name: "Radware Cloud WAF",
	}, {
		URL:  "https://status.rapid7.com",
		Name: "Rapid7",
	}, {
		URL:  "https://help.resolver.com/help/status-dashboard",
		Name: "Resolver",
	}, {
		URL:  "https://status.rhombus.com",
		Name: "Rhombus",
	}, {
		URL:  "https://status.ribose.com",
		Name: "Ribose",
	}, {
		URL:  "https://status.rubrik.com",
		Name: "Rubrik",
	}, {
		URL:  "https://status.runpanther.io",
		Name: "Runpanther",
	}, {
		URL:  "https://status.safebase.io",
		Name: "SafeBase",
	}, {
		URL:  "https://status.sailpoint.com",
		Name: "SailPoint",
	}, {
		URL:  "https://sectigo.status.io",
		Name: "Sectigo",
	}, {
		URL:  "https://status.securecodewarrior.com",
		Name: "Secure Code Warror",
	}, {
		URL:  "https://status.secureframe.com",
		Name: "Secureframe",
	}, {
		URL:  "https://status.securew2.com",
		Name: "SecureW2",
	}, {
		URL:  "https://status.ctpx.secureworks.com",
		Name: "Secureworks",
	}, {
		URL:  "https://status.securityscorecard.com",
		Name: "SecurityScorecard",
	}, {
		URL:  "https://status.securitytrails.com",
		Name: "SecurityTrails",
	}, {
		URL:  "http://status.securly.com",
		Name: "Securly",
	}, {
		URL:  "https://status.semgrep.dev",
		Name: "Semgrep",
	}, {
		URL:  "https://status.seon.io",
		Name: "SEON",
	}, {
		URL:  "https://sertifi.statuspage.io",
		Name: "Sertifi",
	}, {
		URL:  "https://status.sift.com",
		Name: "Sift",
	}, {
		URL:  "https://status.skyhighsecurity.com",
		Name: "Skyhigh Security",
	}, {
		URL:  "https://smartpass.instatus.com",
		Name: "SmartPass",
	}, {
		URL:  "https://status.smarty.com",
		Name: "Smarty",
	}, {
		URL:  "https://status.smoothwall.com",
		Name: "Smoothwall",
	}, {
		URL:  "https://status.smxemail.com",
		Name: "SMX Cybersecure Email",
	}, {
		URL:  "https://status.snyk.io",
		Name: "Snyk",
	}, {
		URL:  "https://centralstatus.sophos.com",
		Name: "Sophos",
	}, {
		URL:  "https://status.specopssoft.com",
		Name: "SpecOPs",
	}, {
		URL:  "https://status.sucuri.net",
		Name: "Sucuri",
	}, {
		URL:  "http://status.us2.sumologic.com",
		Name: "Sumo Logic US2",
	}, {
		URL:  "https://status.tailscale.com",
		Name: "Tailscale",
	}, {
		URL:  "https://uptime.tenable.com",
		Name: "Tenable",
	}, {
		URL:  "https://status.threatstack.com",
		Name: "threat stack",
	}, {
		URL:  "https://status.threatx.com",
		Name: "ThreatX",
	}, {
		URL:  "https://status.threema.ch",
		Name: "Threema",
	}, {
		URL:  "http://status.todyl.com",
		Name: "Todyl",
	}, {
		URL:  "https://status.tokenex.com",
		Name: "TokenEx",
	}, {
		URL:  "https://tpxcommunications.statuspage.io",
		Name: "TPx Communications",
	}, {
		URL:  "https://status.transcend.io",
		Name: "Transcend",
	}, {
		URL:  "https://status.trendmicro.com/s/en-US/",
		Name: "Trend Micro",
	}, {
		URL:  "https://www.trugrid.com/status",
		Name: "TruGrid",
	}, {
		URL:  "https://status.tugboatlogic.com",
		Name: "Tugboat Logic",
	}, {
		URL:  "https://status.urlscan.io",
		Name: "Urlscan",
	}, {
		URL:  "https://status.usaepay.com",
		Name: "USAEpay",
	}, {
		URL:  "https://status.vanta.co",
		Name: "Vanta",
	}, {
		URL:  "https://status.veracode.com",
		Name: "Veracode",
	}, {
		URL:  "https://status.verisk.com",
		Name: "Verisk",
	}, {
		URL:  "https://status.verkada.com",
		Name: "Verkada",
	}, {
		URL:  "https://status.verygoodsecurity.com",
		Name: "Very Good Security",
	}, {
		URL:  "https://status.vipre.com",
		Name: "VIPRE",
	}, {
		URL:  "https://status.wallarm.com",
		Name: "Wallarm",
	}, {
		URL:  "https://status.watchguard.com",
		Name: "WatchGuard",
	}, {
		URL:  "https://status.webroot.com",
		Name: "Webroot",
	}, {
		URL:  "https://status.webshrinker.com",
		Name: "Webshrinker",
	}, {
		URL:  "https://main.whoisxmlapi.com/api-status",
		Name: "WhoisXML API",
	}, {
		URL:  "https://status.wickr.com",
		Name: "Wickr",
	}, {
		URL:  "https://status.zerossl.com",
		Name: "ZeroSSL",
	}, {
		URL:  "https://trust.zscaler.com/cloud-status",
		Name: "Zscaler Cloud",
	}, {
		URL:  "https://status.frase.io",
		Name: "Frase",
	}, {
		URL:  "https://status.seomonitor.com",
		Name: "SEOmonitor",
	}, {
		URL:  "https://stackstatus.com",
		Name: "20i",
	}, {
		URL:  "https://status.alphavps.com",
		Name: "AlphaVPS",
	}, {
		URL:  "https://anchorhost.statuspage.io",
		Name: "Anchor Host",
	}, {
		URL:  "https://status.appwrite.io",
		Name: "appwrite",
	}, {
		URL:  "https://anchorhost.statuspage.io",
		Name: "anchor-host",
	}, {
		URL:  "https://automatticstatus.com",
		Name: "automattic",
	}, {
		URL:  "http://status.binarylane.com.au",
		Name: "binary-lane",
	}, {
		URL:  "http://stats.pingdom.com/tdmmfmbt03rn",
		Name: "campuspress",
	}, {
		URL:  "https://status.catalystcloud.nz",
		Name: "catalyst-cloud",
	}, {
		URL:  "https://status.cloudsigma.com",
		Name: "cloudsigma",
	}, {
		URL:  "https://status.convertapi.com",
		Name: "convertapi",
	}, {
		URL:  "https://status.courier.com",
		Name: "courier",
	}, {
		URL:  "https://status.crucial.com.au",
		Name: "crucial-hosting",
	}, {
		URL:  "http://www.dediservestatus.com",
		Name: "dediserve",
	}, {
		URL:  "https://dhostingstatus.com",
		Name: "dhosting",
	}, {
		URL:  "https://www.dpstatus.com",
		Name: "digital-pacific",
	}, {
		URL:  "https://status.dogado.de",
		Name: "dogado",
	}, {
		URL:  "https://status.dongee.com",
		Name: "dongee",
	}, {
		URL:  "https://www.dreamhoststatus.com",
		Name: "dreamhost",
	}, {
		URL:  "https://www.dynstatus.com",
		Name: "dyn",
	}, {
		URL:  "https://status.theendlessweb.com",
		Name: "endless-group",
	}, {
		URL:  "https://status.expo.io",
		Name: "expo",
	}, {
		URL:  "https://fluccs.status.io",
		Name: "fluccs",
	}, {
		URL:  "https://status.getflywheel.com",
		Name: "flywheel",
	}, {
		URL:  "https://status.formassembly.com",
		Name: "formassembly",
	}, {
		URL:  "https://status.fragnet.net",
		Name: "fragnet-networks",
	}, {
		URL:  "https://status.freistilbox.com",
		Name: "freistilbox",
	}, {
		URL:  "https://status.gandi.net",
		Name: "gandi",
	}, {
		URL:  "https://status.getresponse.com",
		Name: "getresponse",
	}, {
		URL:  "https://status.gitlabhost.com",
		Name: "gitlabhost",
	}, {
		URL:  "https://www.godaddy.com/system-status",
		Name: "godaddy",
	}, {
		URL:  "https://status.happyfox.com",
		Name: "happyfox",
	}, {
		URL:  "https://hawkhoststatus.com",
		Name: "hawk-host",
	}, {
		URL:  "https://status.hostedgraphite.com",
		Name: "hosted-graphite",
	}, {
		URL:  "https://status.hostpress.de",
		Name: "HostPress",
	}, {
		URL:  "https://status.hostry.com",
		Name: "Hostry",
	}, {
		URL:  "https://status.inmotionhosting.com",
		Name: "InMotion Hosting",
	}, {
		URL:  "https://www.ionos-status.de",
		Name: "IONOS",
	}, {
		URL:  "http://status.joomag.com",
		Name: "Joomag",
	}, {
		URL:  "https://jostleap.statuspage.io",
		Name: "Jostle AP",
	}, {
		URL:  "https://status.kinsta.com",
		Name: "Kinsta",
	}, {
		URL:  "https://status.kualo.com",
		Name: "Kualo",
	}, {
		URL:  "https://status.liquidweb.com",
		Name: "Liquid Web",
	}, {
		URL:  "https://status.lumaserv.com",
		Name: "LUMASERV",
	}, {
		URL:  "https://status.magemojo.com",
		Name: "MageMojo",
	}, {
		URL:  "https://status.moodle.com",
		Name: "Moodle",
	}, {
		URL:  "https://www.namecheap.com/status-updates",
		Name: "Namecheap",
	}, {
		URL:  "https://status.nexcess.net",
		Name: "Nexcess",
	}, {
		URL:  "https://status.one.com",
		Name: "One",
	}, {
		URL:  "https://status.panoply.io",
		Name: "Panoply",
	}, {
		URL:  "https://status.pantheon.io",
		Name: "Pantheon",
	}, {
		URL:  "https://status.plox.host",
		Name: "PloxHost",
	}, {
		URL:  "https://status.plusserver.com",
		Name: "PlusServer",
	}, {
		URL:  "https://status.presslabs.com",
		Name: "Presslabs",
	}, {
		URL:  "https://status.prismic.io",
		Name: "Prismic",
	}, {
		URL:  "https://status.publit.io",
		Name: "Publitio",
	}, {
		URL:  "https://status.quadranet.com",
		Name: "QuadraNet",
	}, {
		URL:  "https://qualifio.status.io",
		Name: "Qualifio",
	}, {
		URL:  "https://status.apps.rackspace.com",
		Name: "Rackspace Cloud Office",
	}, {
		URL:  "https://status.rackspeed.de",
		Name: "rackSPEED",
	}, {
		URL:  "https://status.rechargepayments.com",
		Name: "ReCharge",
	}, {
		URL:  "https://status.register.it",
		Name: "Register.it",
	}, {
		URL:  "https://status.rocket.net",
		Name: "Rocket.net",
	}, {
		URL:  "https://status.rosehosting.com",
		Name: "RoseHosting",
	}, {
		URL:  "https://status.section.io",
		Name: "Section",
	}, {
		URL:  "https://serveboltstatus.com",
		Name: "Servebolt",
	}, {
		URL:  "https://status.goshippo.com",
		Name: "Shippo",
	}, {
		URL:  "https://status.shockbyte.com",
		Name: "Shockbyte",
	}, {
		URL:  "https://status.shockhosting.net",
		Name: "Shock Hosting",
	}, {
		URL:  "https://www.shopifystatus.com",
		Name: "Shopify",
	}, {
		URL:  "https://status.simplyhosting.com",
		Name: "Simply Hosting & Servers",
	}, {
		URL:  "https://status.squarespace.com",
		Name: "Squarespace",
	}, {
		URL:  "https://summithosting.statuskeeper.io",
		Name: "Summit Hosting",
	}, {
		URL:  "https://status.umbrellar.com",
		Name: "Umbrellar",
	}, {
		URL:  "https://status.velocityhost.com.au",
		Name: "Velocity Host",
	}, {
		URL:  "https://status.vultr.com",
		Name: "Vultr",
	}, {
		URL:  "https://status.webcentral.au",
		Name: "Webcentral",
	}, {
		URL:  "https://status.webscrapingapi.com",
		Name: "WebScrapingAPI",
	}, {
		URL:  "https://wpenginestatus.com",
		Name: "WP Engine",
	}, {
		URL:  "https://status.docebo.com",
		Name: "Docebo",
	}, {
		URL:  "https://status.lunar.app",
		Name: "Lunar",
	}, {
		URL:  "https://portal.office.com/servicestatus",
		Name: "Microsoft",
	}, {
		URL:  "https://www.google.com/appsstatus/dashboard",
		Name: "Google",
	}, {
		URL:  "https://status.axioshq.com",
		Name: "Axios",
	}, {
		URL:  "https://status.enterprisemessaging-starhub.com/?start_date=2023-12-02",
		Name: "StarHub",
	}, {
		URL:  "https://status.minnstate.edu",
		Name: "State of Minnesota",
	}, {
		URL:  "https://status.quiltmc.org",
		Name: "Quilt",
	}, {
		URL:  "https://support.altosoftware.co.uk/hc/en-gb/articles/16715261983633-Alto-Service-Status",
		Name: "Alto Pharmacy",
	}, {
		URL:  "http://status.sapiensia.com",
		Name: "Sapiens",
	}, {
		URL:  "https://status.mulesoft.com",
		Name: "MuleSoft",
	}, {
		URL:  "http://status.stealth.net.au",
		Name: "Stealth",
	}, {
		URL:  "https://status.sse.cisco.com",
		Name: "Cisco Systems",
	}, {
		URL:  "https://status.amsoil.com",
		Name: "AMSOIL INC.",
	}, {
		URL:  "https://portal.office.com/servicestatus",
		Name: "Microsoft ",
	}, {
		URL:  "https://status.okta.com",
		Name: "Okta",
	}, {
		URL:  "https://status.amp.cisco.com",
		Name: "Cisco",
	}, {
		URL:  "https://docs.servicenow.com/bundle/washingtondc-platform-user-interface/page/build/service-portal/concept/service-status-widget.html",
		Name: "ServiceNow",
	}, {
		URL:  "https://status.openai.com",
		Name: "OPEN",
	}, {
		URL:  "https://status.adobe.com",
		Name: "Adobe",
	}, {
		URL:  "https://status.cloud.yandex.com",
		Name: "Yandex",
	}, {
		URL:  "https://status.redis.com",
		Name: "Redis",
	}, {
		URL:  "https://uptime.com/trendyol.com",
		Name: "Trendyol Group",
	}, {
		URL:  "https://portal.office.com/servicestatus",
		Name: "Microsoft",
	}, {
		URL:  "https://status.weendeavor.com",
		Name: "Endeavor",
	}, {
		URL:  "https://status.securityscorecard.com",
		Name: "SecurityScorecard",
	}, {
		URL:  "https://status.booksy.com",
		Name: "Booksy",
	}, {
		URL:  "https://portal.office.com/servicestatus",
		Name: "Microsoft",
	}, {
		URL:  "https://status.exact.com",
		Name: "Exact",
	}, {
		URL:  "https://status.trellix.com",
		Name: "Trellix",
	}, {
		URL:  "https://thg.statuspal.io",
		Name: "THG",
	}, {
		URL:  "https://portal.office.com/servicestatus",
		Name: "Microsoft",
	}, {
		URL:  "https://status.cloudera.com",
		Name: "Cloudera",
	}, {
		URL:  "https://status.upwork.com",
		Name: "Upwork",
	}, {
		URL:  "https://status.trustedhealth.com",
		Name: "Trusted Health",
	}, {
		URL:  "https://statusgator.com/services/sonatype",
		Name: "Sonatype",
	}, {
		URL:  "https://issitedownrightnow.com/status/bancolombia.com",
		Name: "Bancolombia",
	}, {
		URL:  "https://status.verisk.com",
		Name: "Verisk",
	}, {
		URL:  "https://status.salesforce.com",
		Name: "salesforce.com",
	}, {
		URL:  "https://degreed.statuspage.io",
		Name: "Degreed",
	}, {
		URL:  "https://status.connectwise.com",
		Name: "ConnectWise",
	}, {
		URL:  "https://status.cohesity.com",
		Name: "Cohesity",
	}, {
		URL:  "https://www.opengovstatus.com",
		Name: "OpenGov Inc.",
	}, {
		URL:  "https://www.isitdownrightnow.com/laredoute.fr.html",
		Name: "La Redoute",
	}, {
		URL:  "https://status.redhat.com",
		Name: "Red Hat",
	}, {
		URL:  "https://www.isitdownrightnow.com/cargurus.com.html",
		Name: "CarGurus",
	}, {
		URL:  "https://status.payscale.com",
		Name: "Payscale",
	}, {
		URL:  "https://status.amp.cisco.com",
		Name: "Cisco",
	}, {
		URL:  "https://iridiumwhere.com/status",
		Name: "Iridium",
	}, {
		URL:  "https://status.redis.com",
		Name: "Redis",
	}, {
		URL:  "https://status.appen.com",
		Name: "Appen",
	}, {
		URL:  "https://status.axway.com",
		Name: "Axway",
	}, {
		URL:  "https://issitedownrightnow.com/status/pinelabs.com",
		Name: "Pine Labs",
	}, {
		URL:  "https://statuspage.openground.bentley.com",
		Name: "Bentley Systems",
	}, {
		URL:  "https://status.matrix.org",
		Name: "Matrix",
	}, {
		URL:  "https://www.saashub.com/atos-status",
		Name: "Atos",
	}, {
		URL:  "https://portal.office.com/servicestatus",
		Name: "Microsoft",
	}, {
		URL:  "https://status.brex.com",
		Name: "Brex",
	}, {
		URL:  "https://status.snowflake.com",
		Name: "Snowflake",
	}, {
		URL:  "https://cloud.ibm.com/status",
		Name: "IBM",
	}, {
		URL:  "https://status.salesforce.com",
		Name: "Salesforce",
	}, {
		URL:  "https://statusgator.com/services/docker",
		Name: "Docker, Inc",
	}, {
		URL:  "https://status.me.sap.com",
		Name: "SAP",
	}, {
		URL:  "https://www.githubstatus.com",
		Name: "GitHub",
	}, {
		URL:  "https://status.multiversx.com",
		Name: "Multiverse",
	}, {
		URL:  "https://updownradar.com/status/avito.ru",
		Name: "Avito",
	}, {
		URL:  "https://status.zoominfo.com",
		Name: "ZoomInfo",
	}, {
		URL:  "https://www.isitdownrightnow.com/bloomberg.com.html",
		Name: "Bloomberg",
	}, {
		URL:  "https://connectedfleet.michelin.com/en/status",
		Name: "MICHELIN Connected Fleet",
	}, {
		URL:  "https://status.entrata.com",
		Name: "Entrata",
	}, {
		URL:  "https://statusgator.com/services/rippling",
		Name: "Rippling",
	}, {
		URL:  "https://www.isitdownrightnow.com/youtube.com.html",
		Name: "YouTube",
	}, {
		URL:  "https://status.ucsb.edu",
		Name: "UC Santa Barbara",
	}, {
		URL:  "https://status.harness.io",
		Name: "Harness",
	}, {
		URL:  "https://status.connect.aveva.com",
		Name: "AVEVA",
	}, {
		URL:  "https://www.collibra.com/us/en/status-dashboard",
		Name: "Collibra",
	}, {
		URL:  "https://status.vmware-services.io",
		Name: "VMware",
	}, {
		URL:  "https://status.neo4j.io",
		Name: "Neo4j",
	}, {
		URL:  "https://docaposte.betteruptime.com",
		Name: "Docaposte",
	}, {
		URL:  "https://status.globant.com/login",
		Name: "Globant",
	}, {
		URL:  "https://status.toasttab.com",
		Name: "Toast",
	}, {
		URL:  "https://status.astra.datastax.com",
		Name: "DataStax",
	}, {
		URL:  "https://status.udemy.com",
		Name: "Udemy",
	}, {
		URL:  "https://status.snyk.io",
		Name: "Snyk",
	}, {
		URL:  "https://status.twitch.com",
		Name: "Twitch",
	}, {
		URL:  "https://www.calendlystatus.com",
		Name: "Calendly",
	}, {
		URL:  "https://status.sse.cisco.com",
		Name: "Cisco",
	}, {
		URL:  "https://status.postman.com",
		Name: "Postman",
	}, {
		URL:  "https://www.cloudflarestatus.com",
		Name: "Cloudflare, Inc.",
	}, {
		URL:  "https://www.contentfulstatus.com",
		Name: "Contentful",
	}, {
		URL:  "https://status.redhat.com",
		Name: "Red Hat",
	}, {
		URL:  "https://status.kore.com",
		Name: "Kore.ai",
	}, {
		URL:  "https://www.cloudbeesstatus.com",
		Name: "CloudBees",
	}, {
		URL:  "https://status.quantcast.com",
		Name: "Quantcast",
	}, {
		URL:  "https://status.cloudera.com",
		Name: "Cloudera",
	}, {
		URL:  "https://status.okta.com",
		Name: "Okta",
	}, {
		URL:  "https://status.fourkites.com",
		Name: "FourKites, Inc.",
	}, {
		URL:  "https://status.cint.com",
		Name: "Cint",
	}, {
		URL:  "https://www.ionos-status.com",
		Name: "IONOS",
	}, {
		URL:  "https://status.modeanalytics.com",
		Name: "Mode",
	}, {
		URL:  "https://status.cashfree.com",
		Name: "Cashfree Payments",
	}, {
		URL:  "https://status.one.com",
		Name: "ONE",
	}, {
		URL:  "https://status.epicgames.com",
		Name: "Epic Games",
	}, {
		URL:  "https://status.whatnot.com",
		Name: "Whatnot",
	}, {
		URL:  "https://status.payment.schibsted.io",
		Name: "Schibsted",
	}, {
		URL:  "https://status.manomano.com",
		Name: "ManoMano",
	}, {
		URL:  "https://statusgator.com/services/opentext",
		Name: "OpenText",
	}, {
		URL:  "https://status.cimpress.io",
		Name: "Cimpress",
	}, {
		URL:  "https://status.servicetitan.com",
		Name: "ServiceTitan",
	}, {
		URL:  "https://www.google.com/appsstatus/dashboard",
		Name: "Google",
	}, {
		URL:  "https://discordstatus.com",
		Name: "Discord",
	}, {
		URL:  "https://status.hashicorp.com",
		Name: "HashiCorp",
	}, {
		URL:  "https://status.zenoti.com",
		Name: "Zenoti",
	}, {
		URL:  "https://status.mongodb.com",
		Name: "MongoDB",
	}, {
		URL:  "https://status.check24.de",
		Name: "CHECK24 Vergleichsportal GmbH",
	}, {
		URL:  "https://status.edq.com",
		Name: "Experian",
	}, {
		URL:  "https://status.wealthsimple.com",
		Name: "Wealthsimple",
	}, {
		URL:  "https://status.godaddy.com",
		Name: "GoDaddy",
	}, {
		URL:  "https://status.vistage.com",
		Name: "Vistage Worldwide, Inc.",
	}, {
		URL:  "https://osdatahub.os.uk/serviceStatus",
		Name: "Ordnance Survey",
	}, {
		URL:  "https://status.grammarly.com",
		Name: "Grammarly",
	}, {
		URL:  "https://status.dev.pro",
		Name: "Dev.Pro",
	}, {
		URL:  "https://status.bolt.com",
		Name: "Bolt",
	}, {
		URL:  "https://status.catonetworks.com",
		Name: "Cato Networks",
	}, {
		URL:  "https://status.payoneer.com",
		Name: "Payoneer",
	}, {
		URL:  "https://status.cloud.yandex.com",
		Name: "Yandex",
	}, {
		URL:  "https://status.equinix.com",
		Name: "Equinix",
	}, {
		URL:  "https://trust.emarsys.com",
		Name: "Emarsys",
	}, {
		URL:  "https://status.tokopedia.com",
		Name: "Tokopedia",
	}, {
		URL:  "https://status.box.com",
		Name: "Box",
	}, {
		URL:  "https://status.ripple.moe",
		Name: "Ripple",
	}, {
		URL:  "https://status.linuxfoundation.org",
		Name: "The Linux Foundation",
	}, {
		URL:  "https://status.planview.com",
		Name: "Planview, Inc.",
	}, {
		URL:  "https://status.rubrik.com",
		Name: "Rubrik, Inc.",
	}, {
		URL:  "https://www.similarweb.com/website/statuspage.io",
		Name: "Similarweb",
	}, {
		URL:  "https://status.boomi.com",
		Name: "Boomi",
	}, {
		URL:  "https://status.criteo.com",
		Name: "Criteo",
	}, {
		URL:  "https://status.databricks.com",
		Name: "Databricks",
	}, {
		URL:  "https://status.bmj.com",
		Name: "BMJ",
	}, {
		URL:  "https://status.wiz.io",
		Name: "Wiz",
	}, {
		URL:  "https://status.edg.io",
		Name: "Edgio",
	}, {
		URL:  "https://status.stripe.com",
		Name: "Stripe",
	}, {
		URL:  "https://www.allegrostatus.pl",
		Name: "Allegro",
	}, {
		URL:  "https://status.ifs.com",
		Name: "IFS",
	}, {
		URL:  "https://status.project44.com",
		Name: "project44",
	}, {
		URL:  "https://status.adobe.com",
		Name: "Adobe",
	}, {
		URL:  "https://status.irobot.com",
		Name: "iRobot",
	}, {
		URL:  "https://status.cloud.coveo.com",
		Name: "Coveo",
	}, {
		URL:  "https://status.doctolib.com",
		Name: "Doctolib",
	}, {
		URL:  "https://status.apeople.automationanywhere.com",
		Name: "Automation Anywhere",
	}, {
		URL:  "https://status.1password.com",
		Name: "1Password",
	}, {
		URL:  "https://status.recruitingbypaycor.com",
		Name: "Paycor",
	}, {
		URL:  "https://dynatrace.status.io",
		Name: "Dynatrace",
	}, {
		URL:  "https://kb.acronis.com/tag/status",
		Name: "Acronis",
	}, {
		URL:  "https://status.sinch.com",
		Name: "Sinch",
	}, {
		URL:  "https://status.cloud.com",
		Name: "Cloud Software Group",
	}, {
		URL:  "https://status.lexisnexisrisk.com",
		Name: "LexisNexis",
	}, {
		URL:  "https://status.spotpos.com",
		Name: "Xplor",
	}, {
		URL:  "https://status.cohere.ai",
		Name: "Cohere",
	}, {
		URL:  "https://status.coachhub.com",
		Name: "CoachHub - The digital coaching platform",
	}, {
		URL:  "https://status.cognism.com",
		Name: "Cognism",
	}, {
		URL:  "https://status.owndata.com",
		Name: "Own Company",
	}, {
		URL:  "https://status.constantcontact.com",
		Name: "Constant Contact",
	}, {
		URL:  "https://status.elastic.co",
		Name: "Elastic",
	}, {
		URL:  "https://status.lusha.com",
		Name: "Lusha",
	}, {
		URL:  "https://status.grafana.com",
		Name: "Grafana Labs",
	}, {
		URL:  "https://www.capitalone.com/status",
		Name: "Capital One",
	}, {
		URL:  "http://status.optimissa.com",
		Name: "Optimissa, Capital Markets Consulting",
	}, {
		URL:  "https://status.confluent.cloud",
		Name: "Confluent",
	}, {
		URL:  "https://status.hubspot.com",
		Name: "HubSpot",
	}, {
		URL:  "https://tcpsoftware.com/status",
		Name: "TCP (TimeClock Plus)",
	}, {
		URL:  "https://status.carta.com",
		Name: "Carta",
	}, {
		URL:  "https://status.datavant.com",
		Name: "Datavant",
	}, {
		URL:  "https://status.omadahealth.com",
		Name: "Omada Health",
	}, {
		URL:  "https://status.insights.numerator.com",
		Name: "Numerator",
	}, {
		URL:  "https://status.hunterdouglas.com",
		Name: "Hunter Douglas, Inc.",
	}, {
		URL:  "https://status.amplitude.com",
		Name: "Amplitude",
	}, {
		URL:  "https://status.commercetools.com",
		Name: "commercetools GmbH",
	}, {
		URL:  "https://connectedfleet.michelin.com/en/status",
		Name: "Michelin",
	}, {
		URL:  "https://health.aws.amazon.com/health/status",
		Name: "Amazon",
	}, {
		URL:  "https://status.qualitestgroup.com/Home/Privacy",
		Name: "Qualitest",
	}, {
		URL:  "https://status.twilio.com",
		Name: "Twilio",
	}, {
		URL:  "https://ocistatus.oraclecloud.com/#/",
		Name: "Oracle",
	}, {
		URL:  "https://status.activecampaign.com",
		Name: "ActiveCampaign",
	}, {
		URL:  "https://status.amp.cisco.com",
		Name: "Cisco Systems Argentina",
	}, {
		URL:  "https://status.services.cloud.netapp.com",
		Name: "NetApp",
	}, {
		URL:  "https://status.miro.com",
		Name: "Miro",
	}, {
		URL:  "https://status.hginsights.com",
		Name: "HG Insights",
	}, {
		URL:  "https://status.cohesity.com",
		Name: "Cohesity",
	}, {
		URL:  "https://status.calm.com",
		Name: "Calm",
	}, {
		URL:  "https://status.seek.com",
		Name: "SEEK",
	}, {
		URL:  "https://status.sinch.com",
		Name: "Sinch India",
	}, {
		URL:  "https://status.trade.tt",
		Name: "Trading Technologies",
	}, {
		URL:  "https://status.victoriametrics.com",
		Name: "Managed VictoriaMetrics",
	}, {
		URL:  "https://www.redditstatus.com",
		Name: "Reddit",
	},
}
