version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: statusphere_user
      POSTGRES_PASSWORD: statusphere_password
      POSTGRES_DB: statusphere_db
    ports:
      - "5432:5432"

  scraper:
    build:
      context: ./
      dockerfile: ./scraper/Dockerfile
    environment:
      STATUSPHERE_POSTGRES_HOST: postgres
      STATUSPHERE_POSTGRES_PORT: 5432
      STATUSPHERE_POSTGRES_USER: statusphere_user
      STATUSPHERE_POSTGRES_PASSWORD: statusphere_password
      STATUSPHERE_POSTGRES_DATABASE: statusphere_db
    depends_on:
      - postgres

  apiserver:
    build:
      context: ./
      dockerfile: ./apiserver/Dockerfile
    ports:
      - "8080:80"
    environment:
      STATUSPHERE_POSTGRES_HOST: postgres
      STATUSPHERE_POSTGRES_PORT: 5432
      STATUSPHERE_POSTGRES_USER: statusphere_user
      STATUSPHERE_POSTGRES_PASSWORD: statusphere_password
      STATUSPHERE_POSTGRES_DATABASE: statusphere_db
    depends_on:
      - postgres

  jobrunner:
    build:
      context: ./
      dockerfile: ./jobrunner/Dockerfile
    environment:
      STATUSPHERE_POSTGRES_HOST: postgres
      STATUSPHERE_POSTGRES_PORT: 5432
      STATUSPHERE_POSTGRES_USER: statusphere_user
      STATUSPHERE_POSTGRES_PASSWORD: statusphere_password
      STATUSPHERE_POSTGRES_DATABASE: statusphere_db
    depends_on:
      - postgres